### ISSUE TITLE
JS: Case expression and basic patterns

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1036]
- [x] Case expressions
- [x] Patterns
  - [x] Ints
  - [x] Floats
  - [x] Strings

We don't need optimised pattern compilation. Compiling to a linear scan rather than a tree is OK.

Follows on from https://github.com/gleam-lang/gleam/issues/1034
Follows on from https://github.com/gleam-lang/gleam/issues/1035

**Comment by lpil** [comment]
Very interesting to see how Rescript compiles case without using iife.

https://rescript-lang.org/try?code=DYUwLgBA9gdiEF4IAoB+BjKBXGYBcEAlrgJSIB8EA3gFAQQDOA7oWOgBYSY6S30A+EAIwUIAIljoQYuhEEAmUWLAspMgRADMSsOwBOhNbMExRAIRDAwAOgCSua2CgBlMAZgBzZDDIBqX+IQYIQAtiAM6hAAvjQxNKCQKlCIKBjYuATEYGQIlHwQCRAAHinMrBxc6bzGwkqS0jWKueIqhg0a2s3K+m2RJuaWNvY2Tq7uXj4Q-oHBYRGyMfQA2kUAurE0QA

```rescript
let one = (~count: int) => {
  switch count {
  | 1 => "once"
  | 2 => "twice"
  | 3 => "thrice"
  | n => Belt.Int.toString(n) ++ " times"
  }
}

let two = (~count: int) => {
  let x = switch count {
  | 1 => "once"
  | 2 => "twice"
  | 3 => "thrice"
  | n => Belt.Int.toString(n) ++ " times"
  }
  [x]
}
```

```js
function one(count) {
  switch (count) {
    case 1 :
        return "once";
    case 2 :
        return "twice";
    case 3 :
        return "thrice";
    default:
      return String(count) + " times";
  }
}

function two(count) {
  var tmp;
  switch (count) {
    case 1 :
        tmp = "once";
        break;
    case 2 :
        tmp = "twice";
        break;
    case 3 :
        tmp = "thrice";
        break;
    default:
      tmp = String(count) + " times";
  }
  return [tmp];
}
```

**Comment by CrowdHailer** [comment]
Interesting that Rescript uses if/else not switch if guards are involved.

https://rescript-lang.org/try?code=DYUwLgBA9gdiEF4IAoB+BjKBXGYBcEAlrgJSIB8EA3gFAQQDOA7oWOgBYSY6S30A+EAIwUIAIljoQYuhEEAmUWLAspMgRADMSsOwBOhNbMExRAIRDAwAOgCSua2CgBlMAZgBzZDDIBqX+IQYIQAtiAM6hAAvjQxNKCQKlCIKBjYuATEYGQIlHwQCRAAHinMrBxc6bzGwkqS0jWKueIqhg0a2s3K+m2RJuaWNvY2Tq7uXj4Q-oHBYRGyMfQA2kUAurE0QA

```rust
let one = (~count: int) => {
  switch count {
  | x if x < 2 => "small"
  | 2 => "two"
  | n if n > 2 => "many"
  }
}
```

```js
// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function one(count) {
  if (count < 2) {
    return "small";
  }
  if (count === 2) {
    return "two";
  }
  if (count > 2) {
    return "many";
  }
  throw {
        RE_EXN_ID: "Match_failure",
        _1: [
          "playground.res",
          2,
          2
        ],
        Error: new Error()
      };
}

exports.one = one;
/* No side effect */
```

Also interesting that it tries but not very well to do exhausiveness checking. the following program gets a warning. Despite the fact all cases are in fact covered.

```
[W] Line 2, column 2:

You forgot to handle a possible case here, for example: 
  0
(However, some guarded clause may match this value.)
```

**Comment by lpil** [comment]
> Also interesting that it tries but not very well to do exhausiveness checking. the following program gets a warning. Despite the fact all cases are in fact covered.

Exhaustiveness checking that involves guards requires solving the halting problem, so most languages don't try AFAIK. We might be able to handle small things like `==`, that could be cool

**Comment by lpil** [comment]
If `if` is used for guards I wonder why they ever render `case`. Is it faster or something?

**Comment by CrowdHailer** [comment]
Notes on trying to implement case. This is a summary from https://discord.com/channels/768594524158427167/811254431051808778/842416317163503637

The current approach uses if/else if and assigns variables within the block.
i.e.
```rust
case x {
  #(1, a) -> "foo"
  #(a, b) -> "bar"
}
```
```js
if (x[0] === 1) {
  let a = x[1];
  "foo"
} else if(true) {
  let a = x[0];
  let b = x[1];
  "bar"
}
```

This approach has several problems when dealing with guards and alternative patterns. Question does ReScript/PureScript have alternative patterns.

### Problems with guards
```rust
case x {
  #(1, a) if a > 2 -> "foo"
  #(a, b) -> "bar"
}
```

Because assignment of `a` is after the condition has been evaluated, there are two sub standard options.
1. Have a secondary if statement.
  ```js
  if (x[0] === 1) {
    let a = x[1];
    if (a > 2) {
      "foo"
    } else {
      // What? render all following clauses again
    }
  }
  ```
2. Don't use the assignment
  ```js
  if (x[0] === 1 && x[0] > 2) {
    let a = x[1];
    "foo"
  }
  ```
  The `a` is never used, removing assigning variables that are only used in guards requires complexity to track used variables through out the rest of the block. There is also some complexity by tracking `a` should be rendered as `x[0]` in all subsequent guards, this also makes the generated code more complex to look at.

### Problems with alternative patterns
```rust
case t {
  #(1, a) | #(a, 1) -> a
}
```
let assignments can't be used inside a single code block as in each case the assignment should be different. Solutions could be
1. Just have a separate block for each alternative pattern.
  ```js
  if (t[0] === 1) {
    let a = t[1];
    // there could be a lot of duplicated code here
    a
  } else if (t[1] === 1) {
    let a = t[0];
    // there could be a lot of duplicated code here
    a
  }
  ```
2. Have assignment in the condition block. (more details in last section)
```js
  let a;
  if (
    (t[0] === 1 && (a = t[1], true)) ||
    (t[1] === 1 && (a = t[0], true))
  ) {
    a
  }
  ```
  This approach could also solve the guards problems as the guard can be written using the variable a in place of the true statement above.
  Unfortunately the let has to be declared outside the branch block, therefore the variable will be in scope out side the case blocks. This is not a big problem but it does mean incrementing variables for each arm. i.e.

## Have assignment in the condition block.
Showing have variables numbers would have to increment
```rust
let a = case t {
  #(a, 1) | #(a, 2) -> "ok"
  #(1, x) if x > 1 -> {
    let a = "result"
    a
  }
}
```
```js
let a, a$1, x;
let gleam$output;
if (
  (t[1] === 1 && (a = t[0], true)) ||
  (t[1] === 2 && (a$1 = t[0], true))
) {
  gleam$output = "ok";
} else if (
  (t[0] === 1 && (x = t[1], x > 1))
){
  let a$3 = "result";
  gleam$output = a$3;
}
let a$4 = gleam$output;
```

**Comment by tynanbe** [comment]
What about abstracting out a global Gleam case function, then passing enclosures to it to keep the scope in check?

```rust
let a = case t {
  #(a, 1) | #(a, 2) -> "ok"
  #(1, x) if x > 1 -> {
    let a = "result"
    a
  }
}
```

```javascript
gleam$case = (t, cases) => {
  for (i = 0; i < cases.length; i++) {
    let out = cases[i](t)
    if (out?.length === 2 && out[0]) {
      return out[1]
    }
  }
}

(() => {
let t = [1, 3]

let a = gleam$case(t, [
  t => {
    let a
    if ((t[1] === 1 && (a = t[0], true))
    || (t[1] === 2 && (a = t[0], true))) {
      return [1, "ok"]
    }
  },
  t => {
    let x
    if (t[0] === 1 && (x = t[1], true) && x > 1) {
      let a = "result"
      return [1, a]
    }
  },
])

console.log(a)
})()
```
