### ISSUE TITLE
JS: Anonymous functions

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1041]
Not including capture syntax

**Comment by CrowdHailer** [comment]
Is not including capture syntax because capture syntax is just syntactic sugar and doesn't need any special printing? This was the conclusion I reached on my previous PR
https://github.com/gleam-lang/gleam/pull/1027/files#diff-05eb347e16ba4d984db0b9f737a000a1a2845d0e8131b93f0b2ba0e8c6e83478R517-R542

Note that what does need to happen is to allow use `gleam$capture` in JS rather than `gleam@capture` because `@` is not allowed in variable names.

**Comment by lpil** [comment]
Yup that's right, it gets expanded before this stage

**Comment by lpil** [comment]
> Note that what does need to happen is to allow use gleam$capture in JS rather than gleam@capture because @ is not allowed in variable names.

Well spotted. I'm not super happy with this magic string, perhaps there is a better option here.

**Comment by CrowdHailer** [comment]
Could you have an enum with to_js and to_erl

```rust
enum HiddenVar {
  Tmp
  Capture
}

to_js -> "gleam$".append(name)
to_erl -> "gleam@.append(name)
```
That's very pseudo cody but some such.
