### ISSUE TITLE
Add a CLI option to type check a project/file.

### ISSUE THREAD

**Issue by pd-andy** [gleam-lang/gleam#1063]
I think it would be useful if we had some sort of `gleam check` command to type check an individual file or entire project. Probably not very useful to use directly but I think it would open the doors for additional tooling like a language server or an `elm-review`-style static analysis tool.

If we wanted tooling like that at the moment we'd have to run the compiler and:
* needlessly run the whole compiler and emit BEAM byte code we don't care about
* potentially invest some effort in parsing the compiler output in cases of errors.

Instead we could just run the type checker and possibility emit any errors as JSON for tooling to consume.

**Comment by shunjilin** [comment]
Would an intermediate solution be useful?

I am thinking of just extending the `build_command` function to accept a `generate_target: bool` option which toggles the generation of erlang source on/off, so that running `gleam check` can take advantage of that.

As for the JSON format that might be a next step, and probably depends on how the tooling would need to consume it?
I guess it would be similar to how you can pass `--mesage-format json` for rust's cargo build/check?

**Comment by lpil** [comment]
I think I'd like to wait until we've got the first version of the build tool somewhat working before we tackle this one as I'm likely to change things a lot and break stuff.
