### ISSUE TITLE
Permit `gleam new` to accept `.` as the path

### ISSUE THREAD

**Issue by Takashiidobe** [gleam-lang/gleam#1088]
If i try to create a gleam project in an existing directory with `gleam new .`, I get this error:

```
error: Invalid project name

We were not able to create your project as `.` is
does not have the correct format. Project names must start
with a lowercase latter and may only contain lowercase letters
and underscores.

Please try again with a different project name.
```

I am on mac OS X catalina, with gleam version 0.11.2.

if I try the same with something like cargo, I can run `cargo init .` and it will create a project with the name of the current directory, in the current directory.

I'm wondering if that functionality is wanted as a convenience method to build projects.

**Comment by lpil** [comment]
Let's make `gleam new` accept that by looking at the directory name.

I think it would also be worth changing the project_root argument to be mandatory and the name to be optional and a flag rather than a positional argument. i.e. `gleam new path/to/place --name mylib`. If --name is not given we can use the directory name.
