### ISSUE TITLE
Gleam javascript target crashes when importing core libs

### ISSUE THREAD

**Issue by G4BB3R** [gleam-lang/gleam#1165]
Used this template:
https://github.com/gleam-lang/template-gleam-javascript

SSCE:

main.gleam
```
 // If I comment this line, it compiles
import gleam/float

pub fn main() {
  Nil
}

```
Output:
![image](https://user-images.githubusercontent.com/6143964/122648489-eb6d9f80-d0ff-11eb-97e2-3ecc98b8beee.png)

**Comment by lpil** [comment]
Thank you for the report! I have not looked into this yet but I suspect this happens when there is only a single Gleam module in the project. The toposort function doesn't verify the deps exist as it doesn't need to process the node when there is only one.

To fix this we can replace the call to `fatal_compiler_bug` here to instead return the appropriate module-not-found error.

**Comment by lpil** [comment]
I believe this may be the same issue: https://github.com/gleam-lang/gleam/issues/1146

**Comment by lpil** [comment]
Closing this in favour of the other issue. Thank you!
