### ISSUE TITLE
Should module function type annotations always be required?

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1218]
Currently we are like Elm, Haskell, and OCaml in that type annotations are not required, but they can be given.

```rust
pub fn main(name) { ... }

// or

pub fn main(name: String) { ... }

// or

pub fn main(name: String) -> Int { ... }
```

In real-world code written in these languages type annotations are almost always given for top level functions, and in Elm the compiler will complain if you do not supply them.

Other popular languages with static type systems always require type annotations for top level functions. i.e. Rust, Scala, Kotlin, Go.

With annotated function arguments we can provide easier to understand messages when there is a type error.

~~It would also make it trivial to introduce mutual recusion, remove the need for functions to be defined in the order they are used, and enable some fancier type features in addition.~~ This is done now.

Lastly I think having more certainty in the types when being inferred would open the door to some overloading or implicit typing features that would otherwise introduce ambiguity.

The cost of requiring these annotations is that there is more boilerplate for the programmer, though not an unusual amount for a statically typed language.

I'm interested in hearing what other people think about this question.

**Comment by lpil** [comment]
# New motivation

People are currently frequently surprised by the way that Gleam will generalise functions differently if there are no type annotations and if the function is used before it was defined.

Always having annotations would avoid this issue, and it would make the type checker simpler.

**Comment by pd-andy** [comment]
> People are currently frequently surprised by the way that Gleam will generalise functions differently if there are no type annotations and if the function is used before it was defined.

eg in #1096!

**Comment by resolritter** [comment]
I want to resurface a viewpoint similar to the one brought up in https://github.com/gleam-lang/gleam/issues/1218#issuecomment-568440631, specifically this part:

> what about a middle ground where you can turn on a sort of strict-mode in the compiler that will require these annotations if your team decides they want to go that route

I'll being with context for my stylistic preference, but keep in mind it's not advocating for either side, rather it's just some context for the main point at the end of this post.

As aforementioned, TypeScript does require explicit function signatures even in strict mode. That being said you can totally enforce this for your project using linter rules:

- [explicit-module-boundary-types.md](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md)
- [explicit-function-return-type](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-function-return-type.md)

I personally do not use either of those rules for my projects. In strict mode (which I use), however, the following signature is not allowed:

`function foo(bar, baz) { }`

because `bar` and `baz` are automatically assigned the `Any` type and that is an error for strict mode, which incorporates [noImplicitAny](https://www.typescriptlang.org/tsconfig#noImplicitAny). As a result, all my functions look like the following:

`function foo(bar: Type, baz: Type) { }`

I enjoy the freedom of explicit function signatures being opt-in through linter rules rather than being imposed by the language. In my opinion it definitely is useful to have parameters' types be annotated so that the reader doesn't assume "Any" for everything (an unpleasant experience for exploring complicated functions and complex modules in dynamic languages), but **personally**, stylistically, I don't feel like inclined to type out the return type for brevity's sake; typing the input parameters is definitely enough help for the compiler to figure out the return type by itself. It also feels like a drag for short functions (which come up very often):

`function foo(bar: Type) { baz() /* I would have to say the return type is "void" here, when it's obvious */ }`

Nevertheless, the point of this post is not to advocate for imposing (or not) having full signatures, but rather show that the freedom for varying degrees of verbosity is great. Basically, in TypeScript you can go with either:

1. No annotations: `function foo(bar) { }`

2. Only parameters annotated: `function foo(bar: Type) { }`

3. Fully annotated: `function foo(bar: Type): void { }`

In Gleam, for simplicity's sake in the compiler, while you may want to go in the direction of requiring full signatures for everything rather than having to support different degrees of verbosity, it definitely is worthwhile to at least consider this "stylistic flexibility" aspect. People come from different backgrounds and have different opinions about how they want to write their code, so I'd say having an opt-in `require-full-function-signature` for folks who want it, but leaving as it is for those who don't, would be cool.

Again, I'm not interested in the merits of having vs. not having full signatures, but instead trying to emphasize that the flexibility matters for some. It would not be a deterrent for me if Gleam would go the "fully verbose" route (and I doubt it would for others), although it definitely is not my preference.
