### ISSUE TITLE
String interpolation

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1473]
Prior discussion: https://github.com/gleam-lang/gleam/discussions/1086

## Syntax

```ocaml
let name = "Joe"
let messge = "Hello, ${name}!"
```

Here a variable is used with the `${}` interpolation syntax, but any arbitrary Gleam expression is permitted.

## Erlang output

```erlang
Name = <<"Joe">>,
Message = <<"Hello, "/utf8, Name/binary, "!"/utf8>>.
```

## JavaScript output

```javascript
let name = "Joe"
let messge = `Hello, ${name}!`
```

## Typing

The interpolated expression within the `${}` must be of type `String`. In future we could permit other types, but not for this first version.

## AST

I suggest that this AST node could be represented like so:

```rust
StringInterpolation {
  location: SrcSpan,
  segments: Vec<Expression>
}
```

When performing code generation we can check to see if each expression is a string literal or not and have a special case for that in order to get the right output syntax.

The implementor may determine that there is a better representation.

**Comment by J3RN** [comment]
Few implementation notes, feel free to correct me @lpil 
- Using double quotes `"` instead of backticks (a la JavaScript) <code>`</code>, the lexer will be a bit more exciting :grin:
- I assume these should all be valid and interpreted as verbatim text:
  - `"Hello ${name"`
  - `"Hello $name}"`
  - `"Hello {name}"`
- Guessing these are errors:
  - `"Hello ${}"`
  - `"Hello ${"Dr. ${name}"}"`

**Comment by lpil** [comment]
-    "Hello ${name" : parse error, unexpected EOF
-    "Hello $name}" : string
-    "Hello {name}" : string
-    "Hello ${}" : parse error, unexpected `{`
-    "Hello ${"Dr. ${name}"}" : discouraged but valid nested interpolation

**Comment by J3RN** [comment]
> discouraged but valid nested interpolation

I'm assuming this is because the string interpolation is interpreted as a literal? Or do we want arbitrary expressions inside of interpolation? e.g.
```
"Hello, ${string.append("Wor", "ld")}"
```

**Comment by lpil** [comment]
Yes that's right, any arbitrary expression is to be permitted within `${}`, similiar to Elixir, JavaScript or Ruby.

**Comment by lpil** [comment]
Holding off on this as we need to consider how it would fit with string pattern matching.

**Comment by lpil** [comment]
Closing this because I would like to see how far we get with `<>` for now.

**Comment by hongquan** [comment]
Please bring up this topic. I think this feature is needed by i18n.

**Comment by lpil** [comment]
@hongquan Could you expand on how it's needed for i18n? So we can understand and be on the same page. Thank you 🙏

**Comment by hongquan** [comment]
@lpil In the i18n, we often need to prepare the translatable strings in a form of full sentence, with placeholders variables. We can not use string concat, because different languages have different order of words in a sentence. For example, we have a string in English:

"I am {n} years old".

The Vietnamese translation will be: "Tôi {n} tuổi".
The Togan translation: "ʻOku ou taʻu {n}".

When we display the translation, we just need to load the template string and replace the placeholder with some variables. It is safer and more correct than translating words by words then concatening.

**Comment by GearsDatapacks** [comment]
You can use the `string.replace` function from the standard library here.

**Comment by lpil** [comment]
Yup! And you couldn't use language level string interpolation as it would be syntax, so you couldn't load it from a file or any external source.

Language level string interpolation has the same limitations as the string concat operator.

**Comment by hongquan** [comment]
Sorry, I used the wrong term. I meant "string formating", not "string interpolation".
