### ISSUE TITLE
Generate package info JSON as part of HTML docs

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1475]
https://github.com/gleam-lang/gleam/blob/b47eb344d9025c82f4f68071d91ac576a35fe6ed/test/package.jsonc

This could be used by external tools to enable searching through documentation, for types, functions, and packages in general.

**Comment by michaeljones** [comment]
Is this a standardised format out of interest or something of your own design? Good either way, just curious.

**Comment by lpil** [comment]
Something I came up with. I'm open to other formats for sure

**Comment by lpil** [comment]
Closing this as we don't have an immediate use for it

**Comment by hayleigh-dot-dev** [comment]
I suggest we re-open this as I have some use-cases for [lustre](https://github.com/lustre-labs/lustre) that would benefit greatly from this information. 

- We'd like for `lustre/try`'s preview server to be able to serve lustre apps from any/many gleam modules. Currently it only supports serving a lustre app defined a module with the same name as the package name, and if the `main` function doesn't produce an actual lustre `App` weird things happen at runtime.

  If we had the package/app info available as JSON we could check the return type of _any_
  module's `main` function and if it returns a lustre `App` we could serve it at that route.

- We're working on a CLI that can bundle lustre components to be used outside of the lustre/gleam ecosystem. Similar to the problem above, it is difficult to detect whether a given module _can_ be bundled as a component. The current approach is to check for a specific named function `register` and also check if it looks like there is a function call to `component(` and proceed based on this best-guess. This is,, obviously not great!

  Related to this we'd like to support the ability to bundle a directory containing many lustre components (this reduces bundle size because they share the same runtime).

Beyond lustre's needs I think exposing this information could serve to improve the official package search index with type-aware searches, as well as the possibility to search packages based on their documentation not just their name/description on hex. As an example how that would be immediately useful to the community, searching for "path" on the official package index only shows `gleam_community_path` but not the much more robust `filepath` package.

**Comment by lpil** [comment]
Thank you!

**Comment by hayleigh-dot-dev** [comment]
As prior art [elm](https://elm-lang.org) support JSON output of their docs. I asked folks there if there were any non-core tooling use cases for this feature (LSP and editor tooling are unofficial, so I assume they benefit greatly from this but its not something that is relevant to us).

One interesting use-case comes from the (very well put-together) [elm-codegen](https://github.com/mdgriffith/elm-codegen/tree/main) which uses the JSON output of the docs to generate type-safe bindings for generating package code.

For example if one wanted to generate `elm/html` code using elm-codegen, the tool can read the api for `elm/html` and produce helpers like:

```elm
Gen.Html.div [ Gen.Html.Attributes.class "hello" ] [ Gen.Html.text "world" ]
```

This sounds like a very interesting area to be able to explore!

**Comment by giacomocavalieri** [comment]
If the format shown as an example is fine, I could start working on this! One thing I think is missing is the actual type name in case of `"Custom"` types:
```diff
// import my_module.{type Foo, Foo}
// pub const constant = Foo(1)
"constant": {
  "documentation": "...",
  "type": {
    "kind": "Custom",
+   "name": "Foo",
    "package": "my_package",
    "module": "my_module",
  }
},
```

**Comment by giacomocavalieri** [comment]
I have a couple questions about this feature:
- Should the compiler always generate this metadata file together with the documentation? Or should this file be generated via a different command?
- Where should the generated file end up? Maybe there could be a command line option to choose its destination (like Elm does: `elm docs --output=docs.json`)? Or should it always end up in a fixed location in the `build` folder?

**Comment by lpil** [comment]
> Should the compiler always generate this metadata file together with the documentation? Or should this file be generated via a different command?

Both. We want a command to generate it (`gleam export package-interface`?) and also it should be included with compiled HTML docs.

> Where should the generated file end up?

When building the docs it should be in the root of the compiled docs directory.

When generating just it we can take a path. I'd be open to having a default path too.

**Comment by hayleigh-dot-dev** [comment]
> When generating just it we can take a path. I'd be open to having a default path too.

I think the common case is some sort of tool(ing) would be invoking the compiler to generate this stuff so having the path be required is no big deal to me.
