### ISSUE TITLE
Generate documentation for Gleam libraries

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#153]
The compiler should be able to render markdown or html documentation from modules compiled. For now we can include the names and type of functions and data structures exported, and later add support for additional textual documentation from comments etc.

**Comment by MainShayne233** [comment]
Is the desired feature something along the lines of Elixir's `@doc`/`exdoc`?

**Comment by lpil** [comment]
To start I would like to create some kind of web page of documentation per module, including a list of all the functions and their type sigs. How this is rendered I'm not sure about yet. Perhaps to start the compiler could create a metadata file in json or toml format for each module, this can then be converted into HTML by a script.

Later I would like to introduce documentation comments in the style of Rust `///`

**Comment by gamebox** [comment]
I'd like to assign this to myself, as discussed on IRC.

**Comment by lpil** [comment]
Great! Thank you!

It would be great if you could share your approach to implementing this feature prior to the PR, so we can ensure everyone is happy with the approach before work starts :)

Thank you

**Comment by gamebox** [comment]
The general approach - with the current parsing strategy in place - is:

1. Pull out doc comments where we know strip out all comments.  lalrpop doesn't seem to like comments.
2. For each module, the doc comments will be added a line at a time.  These comments will be sorted into "blocks" as the are added.
3. These blocks are attached to the module.
4. At compile time, we pull out the blocks, and use them and the typed module to generate a EEP48 compliant data structure.
5. We then collect all of the those "chunks" and map them into individual files in a doc folder.  This will be HTML directly for now.
6. When it makes sense, we can serialize the chunk into a .beam file so that hopefully we can have exdoc render the docs.
