### ISSUE TITLE
Split diagnostic text into error + hints in order to improve presentation in editors

### ISSUE THREAD

**Issue by wesleimp** [gleam-lang/gleam#1532]

**Comment by lpil** [comment]
Hello! What does this mean?

**Comment by wesleimp** [comment]
Most of languages send their hints as a diagnostic event, and not as a plain string. e.g

![image](https://user-images.githubusercontent.com/42675056/156775713-7d7cb440-1b7d-4c45-9772-07bcddc1a75a.png)

We could convert the hint string in `Warning` module to a `Diagnostic` and send warning and hint event together

**Comment by lpil** [comment]
Oh I see! For the first iteration I'd like to focus on getting just the basic functionality ready, we can revisit this and refine the diagnostics emitted at a later date.

**Comment by lpil** [comment]
In the discord we've discovered that vscode ruins the formatting of errors in the problems pane, so we will have to do this.

![image](https://user-images.githubusercontent.com/6134406/156847895-9594fa0a-2d43-498a-9adf-2113a40a12d3.png)

We'll have to redesign the `diagnostic` struct to be a bit more precise rather than having a big blob of text.

**Comment by wesleimp** [comment]
I’ll tackle this one
