### ISSUE TITLE
gleam.toml should set minimum versions for nodejs/otp

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#1582]
When contributing to `gleam/stdlib` `gleam test --target javascript` throw a bunch of failed tests at me. While fixing them I noticed that my node version was 14 not 16 or 17 (aka quite old)

**Comment by lpil** [comment]
We don't have any way of knowing the node or Erlang versions during compilation, so it couldn't be in the gleam toml configuration. It could be useful to have libraries with known requirements to document this in their readme files is though

**Comment by inoas** [comment]
This returns the versions:

```erlang
erlang:system_info(otp_release)
```

```javascript
// on Node.js during runtime
process.version
```

Before running compilation and/or tests, could we not run this if we know which target we compile/test again and compare that value to something specified in `gleam.toml`?

**Comment by lpil** [comment]
The compiler doesn't boot the runtime during the compilation process so there's not a good point to do this, and even if we did that's still not enough to know if the compiled code can be run.

For Erlang the problem is normally what libraries are installed rather than the OTP version, something we can't work out without a lot of work.

The same is true for JavaScript, we don't know what packages are installed, or even if it's using Node as opposed to the browser, deno, or something else.

In both cases we don't know if the system that the code is compiled on is the same as the one it is run on. Really this would need to be a runtime feature, and it would be a lot of work to be implemented. I don't think it would be a good use of developer time for Gleam unfortunately.

**Comment by inoas** [comment]
Okay, so could we add some meta information to a toml file, that is maybe even required, thus that developers need to specify their targets and target runtime versions? Or at least find a convention that libraries (such as gleam/stdlib) should specify minimum versions in written form?

**Comment by lpil** [comment]
A convention sounds good, aye
