### ISSUE TITLE
Language Server request fails on Windows 10

### ISSUE THREAD

**Issue by alexdev-at** [gleam-lang/gleam#1611]
Whenever a request is sent to the language server ony my PC, which is running Windows 10,, an error saying that the path of the specified file cannot be found is returned. I am using VSCode with the gleam plugin.

Here is the complete log:

```
INFO language_server_starting
 INFO gleam_project_detected
 INFO download_deps: locking_build_directory
 INFO download_deps: manifest_not_present
 INFO download_deps: resolving_versions
 INFO download_deps: looking_up_hex_package package="gleeunit"
 INFO download_deps: looking_up_hex_package package="gleam_stdlib"
 INFO download_deps: looking_up_package_release name="gleam_stdlib" version="0.21.0"
 INFO download_deps: looking_up_package_release name="gleeunit" version="0.6.1"
 INFO download_deps: package_in_cache package="gleam_stdlib" version=0.21.0
 INFO download_deps: writing_package_to_target package="gleam_stdlib"
 INFO download_deps: package_in_cache package="gleeunit" version=0.6.1
 INFO download_deps: writing_package_to_target package="gleeunit"
 INFO download_deps: writing_manifest_toml
 INFO sending Begin(WorkDoneProgressBegin { title: "Compiling Gleam", cancellable: Some(false), message: None, percentage: None })
 INFO locking_build_directory
 INFO load{package=gleam_stdlib}: Reading source files
 INFO compile{package=gleam_stdlib}: Parsing source code
 INFO compile{package=gleam_stdlib}: Type checking modules
 INFO compile{package=gleam_stdlib}: Performing code generation
 INFO compile{package=gleam_stdlib}: skipping_entrypoint_generation
 INFO compile{package=gleam_stdlib}: copying_native_source_files
 INFO compile{package=gleam_stdlib}: compiling_erlang
 INFO compile{package=gleam_stdlib}: Writing package metadata to disc
 INFO load{package=gleeunit}: Reading source files
 INFO compile{package=gleeunit}: Parsing source code
 INFO compile{package=gleeunit}: Type checking modules
 INFO compile{package=gleeunit}: Performing code generation
 INFO compile{package=gleeunit}: skipping_entrypoint_generation
 INFO compile{package=gleeunit}: copying_native_source_files
 INFO compile{package=gleeunit}: compiling_erlang
 INFO compile{package=gleeunit}: Writing package metadata to disc
 INFO load{package=gleamcord}: Reading source files
 INFO compile{package=gleamcord}: Parsing source code
 INFO compile{package=gleamcord}: Type checking modules
 INFO compile{package=gleamcord}: Performing code generation
 INFO compile{package=gleamcord}: copying_native_source_files
 INFO compile{package=gleamcord}: skipping_erlang_bytecode_compilation
 INFO compile{package=gleamcord}: Writing package metadata to disc
 INFO sending End(WorkDoneProgressEnd { message: None })
 INFO gleam_toml_changed_so_recompiling_full_project
 INFO download_deps: locking_build_directory
 INFO download_deps: Reading manifest.toml
 INFO download_deps: manifest_up_to_date
 INFO sending Begin(WorkDoneProgressBegin { title: "Compiling Gleam", cancellable: Some(false), message: None, percentage: None })
 INFO locking_build_directory
 INFO loading_precompiled_package package=gleam_stdlib
 INFO loading_precompiled_package package=gleeunit
 INFO load{package=gleamcord}: Reading source files
 INFO compile{package=gleamcord}: Parsing source code
 INFO compile{package=gleamcord}: Type checking modules
 INFO compile{package=gleamcord}: Performing code generation
 INFO compile{package=gleamcord}: copying_native_source_files
 INFO compile{package=gleamcord}: skipping_erlang_bytecode_compilation
 INFO compile{package=gleamcord}: Writing package metadata to disc
 INFO sending End(WorkDoneProgressEnd { message: None })
 INFO sending Begin(WorkDoneProgressBegin { title: "Compiling Gleam", cancellable: Some(false), message: None, percentage: None })
 INFO locking_build_directory
 INFO load{package=gleamcord}: Reading source files
 INFO compile{package=gleamcord}: Parsing source code
 INFO compile{package=gleamcord}: Type checking modules
 INFO compile{package=gleamcord}: Performing code generation
 INFO compile{package=gleamcord}: copying_native_source_files
 INFO compile{package=gleamcord}: skipping_erlang_bytecode_compilation
 INFO compile{package=gleamcord}: Writing package metadata to disc
 INFO sending End(WorkDoneProgressEnd { message: None })
 INFO sending Begin(WorkDoneProgressBegin { title: "Compiling Gleam", cancellable: Some(false), message: None, percentage: None })
 INFO locking_build_directory
 INFO load{package=gleamcord}: Reading source files
 INFO compile{package=gleamcord}: Parsing source code
 INFO compile{package=gleamcord}: Type checking modules
 INFO compile{package=gleamcord}: Performing code generation
 INFO compile{package=gleamcord}: copying_native_source_files
 INFO compile{package=gleamcord}: skipping_erlang_bytecode_compilation
 INFO compile{package=gleamcord}: Writing package metadata to disc
 INFO sending End(WorkDoneProgressEnd { message: None })
[Error - 19:39:18] Request textDocument/formatting failed.
  Message: error: File IO failure

An error occurred while trying to read this file:

    /d%3A/gleamcord/src/gleamcord.gleam

The error message from the file IO library was:

    Das System kann den angegebenen Pfad nicht finden. (os error 3)


  Code: 1 
 INFO sending Begin(WorkDoneProgressBegin { title: "Compiling Gleam", cancellable: Some(false), message: None, percentage: None })
 INFO locking_build_directory
 INFO load{package=gleamcord}: Reading source files
 INFO compile{package=gleamcord}: Parsing source code
 INFO compile{package=gleamcord}: Type checking modules
 INFO compile{package=gleamcord}: Performing code generation
 INFO compile{package=gleamcord}: copying_native_source_files
 INFO compile{package=gleamcord}: skipping_erlang_bytecode_compilation
 INFO compile{package=gleamcord}: Writing package metadata to disc
 INFO sending End(WorkDoneProgressEnd { message: None })
```

**Comment by lpil** [comment]
Thank you

**Comment by lpil** [comment]
Hello! Do you have any instructions for replicating this error? I have been using the LSP on a Windows machine today but I've not been able to replicate the issue.

**Comment by xhh** [comment]
I've replicated this error on Windows 10. Here are the steps:

1. Create a new project with `gleam new hello`
2. Open the created `hello` directory with VS Code (with the Gleam extension installed)
3. In VS Code: open the file `src/hello.gleam`
4. Choose the menu: `File` -> `Save`, that is, just save the file without any modifications
5. This error occurs (`The system can not find the given path`):

![gleam_lsp_error](https://user-images.githubusercontent.com/159740/195964708-ebe5bf79-fdb9-4cca-b4c0-12d8d0e00f43.png)

Interestingly, the error does not occur if you make some modifications and save again.

I also have problem when navigating to warnings/errors. For example:

![gleam_lsp_error2](https://user-images.githubusercontent.com/159740/195964818-6f3488e6-d7a1-47e4-8cd7-3fc7d4fed4b2.png)

When I click the line of `Unused variable`, I get `can not open the editor due to unexpected error: the file is a directory`:

![gleam_lsp_error3](https://user-images.githubusercontent.com/159740/195964854-36431c28-e380-44df-8851-253f5c64204a.png)

**Comment by xhh** [comment]
After some investigation I've found several cases of invalid file path on Windows, making some features not working in VS Code with the Gleam extension, like navigating to the source file on warning/error and goto definition.

In **compiler-cli/src/lsp.rs**, the `path` at [line 199](https://github.com/gleam-lang/gleam/blob/1625f872c1fa7a272530ad8856823d312e4bb470/compiler-cli/src/lsp.rs#L199) and `module.path` at [line 622](https://github.com/gleam-lang/gleam/blob/1625f872c1fa7a272530ad8856823d312e4bb470/compiler-cli/src/lsp.rs#L622) is something like `\\?\D:\demo\hello\src\hello.gleam`. It works by removing the first 4 characters to become `D:\demo\hello\src\hello.gleam`.

(p.s. [in line 971](https://github.com/gleam-lang/gleam/blob/1625f872c1fa7a272530ad8856823d312e4bb470/compiler-cli/src/lsp.rs#L971): `let mut file: String = "file://".into();` seems to need to be changed to use 3 slashes: `file:///`)

The `location.path` at [line 959](https://github.com/gleam-lang/gleam/blob/1625f872c1fa7a272530ad8856823d312e4bb470/compiler-cli/src/lsp.rs#L959) and the `path` at [line 747](https://github.com/gleam-lang/gleam/blob/1625f872c1fa7a272530ad8856823d312e4bb470/compiler-cli/src/lsp.rs#L747) is like `/d%3A/demo/hello/src/hello.gleam`, needing to be changed to `d:/demo/hello/src/hello.gleam`.

I'm not sure how the file paths are like that, and where are the real sources that need to be fixed (so that maybe there are other places that could also be fixed), so I'm not going to write a PR and instead posting my findings here.

**Comment by lpil** [comment]
They come from the language clients and are given as URIs. We are going to need to correct the logic that converts from those into paths as the current one seems to not work at all on windows.
