### ISSUE TITLE
Formatter: Permit pipe operators to render on a single line

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1622]
https://github.com/gleam-lang/gleam/discussions/1619#discussioncomment-2708716

Also related to https://github.com/gleam-lang/gleam/issues/1117 as I think it would be nice to be able to force it to render them on multiples lines.

**Comment by inoas** [comment]
After reading more gleam code I feel it is beneficial to have them on multi lines if
- if the whole expression needs to be broken into multiple lines because of length
- if there are more than 2 `|>`

So for me reading comprehension speed is fast if `foo |> bar` and maybe`foo |> bar |> quux` stay on one line but certainly not if `foo |> bar |> quux |> kek stays on one line`.

hard to read

```gleam
[1, 2, 3] |> from_list |> map(fn(x) { x * 2 }) |> to_list |> io.debug
```

good to read:

```gleam
[1, 2, 3]
|> from_list
|> map(fn(x) { x * 2 })
|> to_list
|> io.debug
```

already hard enough to read:

```gleam
from_list([1, 2, 3, 4]) |> interleave(from_list([11, 12, 13, 14])) |> to_list
```

to me already easier to read:

```gleam
from_list([1, 2, 3, 4])
|> interleave(from_list([11, 12, 13, 14]))
|> to_list
```

So I hope we can keep 2 or 3 `|>` on one line, but not longer pipes even if they did fit.

**Comment by keroami** [comment]
Agreed on the examples, because the operators between the pipes are 'complex' and carry punctuation themselves. Makes it hard to see the flow through the pipes in one glance.

Whereas `data |> sort |> reverse |> dump` is fine for me, specifically when embedded in something else that is spanning multiple lines, but simple enough.

Using lustre,
```
ol(
  [],
  data |> sort |> render_item
)
```
 is a lot better than
```
ol(
  [],
  data
  |> sort
  |> render_item
)```

Maybe it even has to do with the fact that `ol` carries multiple arguments, and multi-line pipes obfuscate that.

And of course when the pipeline becomes more complex, I will extract it into a function. Maybe my example should've exclude the sort and be `items |> render_item` within an `ul`.

**Comment by inoas** [comment]
Maybe as a ruleset we could do:

1. line length, if breaks, break all.
2. if there are 3 or more `|>`, break all.
3. enhancement: if pipes do not contain any discrete, lists, tuples or function bodies, keep up to 5? `foo |> bar |> quux |> batz |> io.debug` is still fine.

**Comment by lpil** [comment]
I would like to start with these rules

1. If the pipeline is too long to fit on one line break it
2. If the pipeline was written on more than 1 line break it

**Comment by inoas** [comment]
I like the 2nd rule because it allows the author some control if they want to have single line or multi line pipes, right?

**Comment by lpil** [comment]
Yup, you got it!
