### ISSUE TITLE
Create an npm package for Gleam highlight JS

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1682]
@lpil will need to do this one

https://github.com/exercism/gleam/issues/23#issuecomment-1174758195

**Comment by aflatter** [comment]
@itsgreggreg Hello! After seeing this issue, I've just migrated the Gleam support for highlight.js over from this repo to a separate one (https://github.com/aflatter/highlight.js-gleam) with the intention of moving it into the `gleam-lang` organization. While doing that, I noticed that you already have your own package doing the same thing (https://www.npmjs.com/package/highlightjs-gleam). In order to move forward, I haven't checked for similarities or differences in the implementation and just decided to go with the implementation in the Gleam repository instead.

Unfortunately I'm not able to publish the package now because the names of our packages are too similar:

```
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/highlight.js-gleam - Package name too similar to existing package highlightjs-gleam; try renaming your package to '@aflatter/highlight.js-gleam' and publishing with 'npm publish --access=public' instead
```

I was wondering: Do you still care about the package? If yes, would you be willing to collaborate? If no, I'd be happy to take over the name on NPM and yield it to @lpil once everything is set up.

**Comment by aflatter** [comment]
FYI: I published to [@gleam-lang/highlight.js-gleam  on NPM](https://www.npmjs.com/package/@gleam-lang/highlight.js-gleam).

**Comment by lpil** [comment]
Sweet! Could you transfer ownership of that organisation to me? I think the core team should control that name ideally

**Comment by aflatter** [comment]
> Sweet! Could you transfer ownership of that organisation to me? I think the core team should control that name ideally

Yeah, that was the plan. Sent you an invite to the email that is in your GitHub profile and I'll make you the owner after you accepted it.

**Comment by lpil** [comment]
Oops, I dropped the ball here and didn't click the link in time. @aflatter could you send another one please? 🙏

**Comment by aflatter** [comment]
@lpil Done

**Comment by lpil** [comment]
Thank you!!

**Comment by aflatter** [comment]
> Thank you!!
> 
> edit: We should probably move the repo into the gleam-lang github org?

Just made you an owner of the npm org.

And sure, let's move the git repo! Just tried to do it right away, but apparently I need the permission to create public repos in the org first.

**Comment by lpil** [comment]
Thank you for this @aflatter , you rock! I've invited you to the new org repo
