### ISSUE TITLE
Syntax to write nested functions in a flat style (promise.then, result.then)

### ISSUE THREAD

**Issue by lucasavila00** [gleam-lang/gleam#1709]
Inspired by the discussion https://github.com/gleam-lang/gleam/discussions/1708

I propose a syntax extension that de-sugars:

from

```gleam
import gleam/result
import gleam/javascript/promise

// Todo: improve with + as syntax
let op2 = with result.then as then {
  then x = Ok("x")
  then y = Ok("y")
  io.println(x)
  io.println(y)
  Ok(string.concat([x, y])
}

let op3 = with promise.then as then {
  then x = promise.resolve("x")
  then y = promise.resolve("y")
  io.println(x)
  io.println(y)
  promise.resolve(string.concat([x, y])
}

```

to

``` gleam
let op2 =
  Ok("x")
  |> result.then(fn(x) {
    Ok("y")
    |> result.then(fn(y) {
      io.println(x)
      io.println(y)
      Ok(string.concat([x, y]))
    })
  })

let op3 =
  promise.resolve("x")
  |> promise.then(fn(x) {
    promise.resolve("y")
    |> promise.then(fn(y) {
      io.println(x)
      io.println(y)
      promise.resolve(string.concat([x, y]))
    })
  })
``` 

or to

```gleam
  let op2 =
    result.then(
      Ok("x"),
      fn(x) {
        result.then(
          Ok("y"),
          fn(y) {
            io.println(x)
            io.println(y)
            Ok(string.concat([x, y]))
          },
        )
      },
    )

  let op3 =
    promise.then(
      promise.resolve("x"),
      fn(x) {
        promise.then(
          promise.resolve("y"),
          fn(y) {
            io.println(x)
            io.println(y)
            promise.resolve(string.concat([x, y]))
          },
        )
      },
    )
``` 

It should work with any user defined type, too.

**Comment by lpil** [comment]
Tagging @hayleigh-dot-dev as I think she is very interested in this.

I could see this being a very powerful and convenience feature to have in the language. The main things I would want to investigate and think through carefully before adding something like this are:

## Ease of use

How does this impact the complexity of the language and how easy it is to learn?

It is important that the language remains as approachable as possible, even if that means language features are a little less expressive and powerful in exchange.

## Parsing

How would the passing of the syntax work? In the specific example I think the parser would need to know that then has become a special keyword once the syntax has been defined.

We could possibly track this state in the parser but I would be interested in exploring other syntaxes in which this is not needed, and also ones in which you do not need to declare the function that you wish to use upfront.

```rust
let op2 = {
  result.then! x = Ok("x")
  result.then! y = Ok("y")
  io.println(x)
  io.println(y)
  Ok(string.concat([x, y])
}

let op3 = {
  promise.then! x = promise.resolve("x")
  promise.then! y = promise.resolve("y")
  io.println(x)
  io.println(y)
  promise.resolve(string.concat([x, y])
}
```

Or perhaps a more general trailing lambda syntax
```rust
let op2 = {
  result.then(Ok("x")) with x
  result.then(Ok("y")) with y
  io.println(x)
  io.println(y)
  Ok(string.concat([x, y])
}

let op3 = {
  promise.then(promise.resolve("x")) with x
  promise.then(promise.resolve("y")) with y
  io.println(x)
  io.println(y)
  promise.resolve(string.concat([x, y])
}
```

## The contract

In high school to use denotation you must implement the bind function, which has a specific and precise interface. I think they could also be value in having a more flexible interface that offers little restrictions beyond the function taking an function as the final argument.

**Comment by hayleigh-dot-dev** [comment]
I like the trailing lambda idea, and I think it's used to good effect in Kotlin and Swift(?). We could be a bit more intentional with the syntax though: generalising the original idea to effectively work for any callback not just monadic bind is a good idea, but the proceeding `with` syntax has some problems in my mind:

• It naturally feels like the body should indent as we're introducing a new scope. Indenting basically just re-introduces the main problem of nested `then`s:
```gleam
result.then(...) with x
  result.then(...) with y
    Ok(x + y)
```
Of course the formatter or whatever could just flatten the nesting but I think it's still worth pointing out because it affects how people think about these things.

• It's kind of possible to just miss the binding when you're scanning over the code. Gleam doesn't have any other proceeding keywords as I can remember, and all other bindings can be read right to left "the result of this expression is bound to the name `x`":
```gleam
let x = result.then(...)
try x = result.then(...)
assert Ok(x) = result.then(...)
```
this new version binds on the right hand side:
```gleam
result.then(...) with x
```
I think it might be easy to miss that `x` is now bound and in scope.

---

With that in mind I'd suggest a form that matches the existing binders:
```gleam
with x <- result.then(...)
```
(replace `<-` with `=` if you think that's necessary.

---

As this is sugar for just writing a normal callback, it's also worth considering how this works for callbacks with >1 arguments:
```gleam
with acc, n <- list.fold(items, 0)
```
is there potential for confusion with tuple destructuring here? On the topic, destructuring _isn't allowed in function arguments_ but it _is_ allowed in all other binders – people will inevitably try to write:
```gleam
with #(x, y) <- result.then(...)
```
If this is pure syntax sugar then we should reject this, but then we run the risk of having confusing rules for pattern matching/destructuring in bindings.

**Comment by lpil** [comment]
Great points Hayleigh. I agree with you that making it look like an assignment would fit better with the language as it is today.

At first I prefer the idea of using `=` over `<-`, that's now I'm leaning towards the arrow as it suggests there is more happening than just a regular assignment.

I like the idea of supporting the structuring with the syntax as I think it would be confusing not to when you can with the other assignments syntaxes.

**Comment by lpil** [comment]
I think we also want to think about whether we want to support blocks and pipes on the right hand side of the assignment.

```rust
with user <- log_in() |> result.then
...
```
and
```rust
with user <- {
  let result = log_in()
  result.then(result)
}
...
```

**Comment by lpil** [comment]
@TanklesXL Has highlighted that `with x <- ...` is the same syntax as Elixir. This could be confusing as the semantics are very different.

@schurhammer has suggested a `let x <- result.then(something())` syntax.

**Comment by lucasavila00** [comment]
I like the idea of working with any functions. `with x = ...` might work well, remembers me of python's context manager and go's defer capabilities.

```gleam
import gleam/io
import gleam/string

pub type File {
  File(read: fn() -> String, write: fn(String) -> Nil)
}

pub fn open_file(path: String, cb: fn(File) -> Nil) -> Nil {
  // open file
  cb(todo)
  // close file
}

pub fn with_tmp_dir(cb: fn(String) -> Nil) -> Nil {
  // todo create tmp dir folder
  cb("/tmp/abc")
  // todo delete tmp dir folder
}

pub fn main() {
  with_tmp_dir(fn(dir) {
    io.println(dir)
    open_file(
      string.concat([dir, "/file_name.txt"]),
      fn(file) {
        file.write("abc")
        io.println("something unrelated")
      },
    )
  })
}
pub fn main2() {
  with dir = with_tmp_dir()
  io.println(dir)
  with file = open_file(dir+"file_name.txt")
  file.write("abc")
  io.println("something unrelated...")
}
```

**Comment by TanklesXL** [comment]
+1 for something like 
`with x = ...`. If we're already adding a keyword I don't see a reason to use `<-`instead of `=`

**Comment by lucasavila00** [comment]
Maybe `with` is not a good name? It resembles python context managers, and what's implemented with it in python won't play well with async code (JS)...

```gleam
import gleam/io
import gleam/string

pub type File {
  File(read: fn() -> String, write: fn(String) -> Nil)
}

pub fn open_file(path: String, cb: fn(File) -> Nil) -> Nil {
  // open file
  cb(todo)
  // close file
}

pub fn main() {
  open_file(
    "file_name.txt",
    fn(file) {
      set_timeout(fn () {
        file.write("abc")
      })
    },
  )
}
pub fn main2() {
  with file = open_file("file_name.txt")
  set_timeout(fn {
    file.write("abc")
  })
}
``` 

In this example the file would be closed before the timeout.
Maybe a `bind` keyword would be better?

**Comment by lpil** [comment]
I'd like to avoid any direct comparisons to Haskell as there is a lot of confusing information there that I don't think will help us achieve our goals, so I don't think bind is the right word.

Very interested in other suggestions!

**Comment by schurhammer** [comment]
Some suggestions
```js
when result = query |> promise.then
cont result = query |> promise.then // as in "continuation"
close result = query |> promise.then // as in "make a closure"
```

**Comment by TanklesXL** [comment]
I actually kind of like `when` here but it might be misconstrued with erlang's `when` keyword for guards

**Comment by inoas** [comment]
some more:

- `given`
- `where`

**Comment by lpil** [comment]
More!

```
let x <- load_user() |> promise.then
let x from load_user() |> promise.then

bind x = load_user() |> promise.then
give x = load_user() |> promise.then
chain x = load_user() |> promise.then

yield x = load_user() |> promise.then
yield x <- load_user() |> promise.then
```

**Comment by lpil** [comment]
Current plan:

```rust
yield x <- call(a, b, c)
```

**Comment by timjs** [comment]
`yield` is used for coroutines to transfer control flow in most languages. Doesn't feel right for me. Maybe `use` as keyword instead of `let`?

But more importantly than syntax are the semantics:
- Will this be a simple transformation like Haskell does with `do`-notation?
- How will we determine which `bind` or `then` to use? A la F#'s [computation expressions](https://en.m.wikibooks.org/wiki/F_Sharp_Programming/Computation_Expressions)? Use some trait/type class? Use implicits?

**Comment by lpil** [comment]
It is purely syntactic and is unrelated to the concept of a monadic bind, though it could be used with it.

Yield is a good word because it yields control of the block to the previous expression. It is like to the try expression in that it is similar to features found in other languages (early returns, yield), but instead it is expression based rather than function based.

**Comment by timjs** [comment]
Ah I now understand what you wanne do. And in that case you don't need to say something like `result.then { ..block with yields.. }` but keep the transformation purely syntactic. See Koka's [with statement](https://koka-lang.github.io/koka/doc/book.html#sec-with).

**Comment by lpil** [comment]
Oh cool! I didn't know Koka had the same feature. Very cool to see.

It is quite reassuring to discover other languages with the same feature after we have designed it independently (Roc also has it)

**Comment by lpil** [comment]
Oh cool! I didn't know Koka had the same feature. Very cool to see.

It is quite reassuring to discover other languages with the same feature after we have designed it independently (Roc also has it)

**Comment by lpil** [comment]
Seems that `with` is used quite a lot in labels so it would be a good amount of work to change them all to use `with` for this feature.

**Comment by timjs** [comment]
My 2cts: I'd still vote `use` to match the other three letter verbs used for binding in Gleam (`let` and `try`). "Use the result of this expression in the following block of code."

**Comment by xhh** [comment]
For `Result`, it seems `try` could also be used in this case:

```gleam
let op2 = {
  try x = Ok("x")
  try y = Ok("y")
  io.println(x)
  io.println(y)
  Ok(string.concat([x, y])
}
```

Taking inspiration from [Roc](https://github.com/roc-lang/roc/blob/main/TUTORIAL.md#tasks), maybe we can do this:

```js
let user <- load_user() |> promise.then
let quote <- load_quote_of_today() |> promise.then

{
  let name <- parse_name(user) |> result.then
  let message <- greeting(name, quote) |> result.map
  string.append(message, "\n")
}
|> promise.resolve
```

which turns to something like:

```gleam
load_user() |> promise.then(fn(user) {
  load_quote_of_today() |> promise.then(fn(quote) {
    {
      parse_name(user) |> result.then(fn(name) {
        greeting(name, quote) |> result.map(fn(message) {
          string.append(message, "\n")
        })
      })
    }
    |> promise.resolve
  })
})
```

**Comment by inoas** [comment]
I also like `enter`.

**Comment by inoas** [comment]
> "Use the result of this expression in the following block of code."

That explanation might work well as a mind model mapped to the keyword.

What would be the analogous explanation for `try`?

I am still favourable to make labels not crash with keywords because else ever keyword addition is a breaking change. But when using a keyword like use over with at this point in time that decision could still be made later.

**Comment by timjs** [comment]
@inoas: Simply "try to evaluate this expression and bind its result if it succeeds, otherwise fail"? Doesn't have to be difficult. 

Also, is there a rational behind using `<-` for bindings in this case? All other binders use `=`. Why should nested function application use a different symbol than `let`, `try`, and `assert` and how should programmers remember this syntax difference? (I think this is confusing!)

**Comment by lpil** [comment]
@timjs Good question, a few reasons:

We wanted to make it clearer that more is happening than an assignment here, it is a lot more complex than `let` or `assert`.

The syntax looked rather alien when the callback accepts no arguments when using `=`.

```rust
use = log.span("logging_in")
...
```

It's not too late to bikeshed over syntax though :)

**Comment by lpil** [comment]
It would introduce parser ambiguities which mean we could never use patterns rather than raw variable names, and we would need to always use parens on the right hand side.

This could be an acceptable restriction but it would mean that `use` will always have to have quite a different syntax from `let` and `assert` which use patterns, and `|>` where parens are optional.

**Comment by inoas** [comment]
> Why should nested function application use a different symbol than let, try, and assert and how should programmers remember this syntax difference? (I think this is confusing!)

I agree that I cannot follow why it then isn't `try a <-`
If there is a good reason to use `<-` for `use` then maybe add `<-` to the try syntax and allow it alongside = and let the formatter replace `=` with `<-` and reprecate try with `=` for 1.0?

Or just use `=` with `use`?

**Comment by lpil** [comment]
I think there's a good chance we'll remove `try` if `use` works out well.

**Comment by timjs** [comment]
It indeed would mean we can only use simple binders and no pattern matching after `use`.

**Comment by timjs** [comment]
Btw. Removing `try` in favour of `use` would mean we'd need to write

```gleam
try int_a = parse_int(a)
try int_b = parse_int(b)
try int_c = parse_int(c)
Ok(int_a + int_b + int_c)
```

as

```gleam
use int_a = parse_int(a) |> result.then
use int_b = parse_int(b) |> result.then
use int_c = parse_int(c) |> result.then
Ok(int_a + int_b + int_c)
```

or change the api of, in this case, the `parse_int` function to accept a continuation.

The first option seems to long to write, and will use extra function calls which are not present in the current desugaring of `try`.
The second defeats the purpose of defining small functions doing just one thing.

Am I missing something that makes `use` over `try` more elegant?
