### ISSUE TITLE
Provide type information in LSP even when the module does not fully type check

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#1767]
Currently the LSP can only provide type information when the code fully type checks. We want it all the time!

To do this we will need to be able to partially type check a module.

1. Unify TypedAst and UntypedAst into one format
    - What should the format be?
    - How do we represent types and other inferred data? `Option<Type>`?
    - We may need to stop expanding sugar syntax such as pipelines. This will be annoying.
2. Have the error path still return AST but collect errors. Type checking is a failure if any errors are stored.

**Comment by cybergsus** [comment]
At Serenity we had the same problem with Jakt. We solved the typechecking part by having an `unknown` type inserted into the typed AST. This would be better represented by `Option<Type>`. We didn't unify the untyped/typed ASTs since the typed AST had a lot more information going on that was being filled by the typechecker, and it had some part of the structure removed.

**Comment by cybergsus** [comment]
There's a lot to be changed here, so I'll start by first introducing `Option<Type>` where the typechecker can fail to unify types, and move from there by propagating the information about optional type and handling it in each case.

**Comment by lpil** [comment]
I wonder if we would also need to make the other parts of the typed AST optional in this case.

Another option would be to make an `Untyped` node which could be used to mount an untyped subtree onto a typed tree.

**Comment by cybergsus** [comment]
Hmmm. I've been experimenting with propagating the information about failure but keeping the results, and I've managed to create a `Fallible` type that acts both as a result type (can be collapsed into a `Result` for convenience), but also acts as a context (collect the errors from other parts that just return `Result`). Due to it storing a `Vec` of errors I've had to write a ton of `.map_err(|e| vec![e])` in other parts of the code that interact with `Result<(), gleam_core::Error>`. So the 'fallible context' that I introduced just for the types turns out to be useful across the whole pipeline. Where can I put it?

**Comment by cybergsus** [comment]
I'll put it in a separate file `src/fallible.rs` for the moment and make only the necessary modifications to the code that stem from making types fallible

**Comment by cybergsus** [comment]
My bad, I was joining two tasks. I'm going to only focus on adding the optional/unknown type to the typechecker.

**Comment by cybergsus** [comment]
I've opened #1867 to discuss the implementation of unknown types.

**Comment by lpil** [comment]
Hey @cybergsus ! Thanks for waiting, I've been super overloaded and am slowly getting through all the issues and PRs in my inbox.

I think the way to go here is to have the typer always return an analysed AST which is either fully or partially typed, along with zero or more errors. With this we can then continue traversing the AST rather than exiting early. This initial version can be quite coarse grained- we could consider a module function entirely typed or not and then we can incrementally improve on that in later versions.

I don't think we should change the result type, and we shouldn't need to change the result type or error type beyond making the type error variant contain multiple type errors.

**Comment by cybergsus** [comment]
There was no change needed for 'partial types' as unknown types are represented with unbound variables. I did that to try and avoid producing extra errors when something is unknown. The downside is that we don't know if an error was truly reported or not in that case. I also thought of including a type that included the error(s), but couldn't come up with a solution to recover the errors from the AST in order to produce them that was simple enough.

Regarding the result type, it *has* to be changed, although not in every place. The reason is that Result conveys exclusivity, i.e when an error happens we have no valid data. But what we want to introduce is "hey, I had a bunch of errors, but I could manage to produce data that can be useful". In my naive mind, the LSP would get the errors AND the data, and the rest of the compiler pipeline (which I have taken care of) purposefully 'collapses' the `FilledResult` to a single `Result` that only gives the data when there are no errors (see https://github.com/gleam-lang/gleam/blob/965addbe01208d17261bcd9965e5f32d280238cc/compiler-core/src/filled_result.rs#L55), so that any errors at that point can be forwarded with the regular `Result`.

**Comment by lpil** [comment]
> There was no change needed for 'partial types' as unknown types are represented with unbound variables:

Not partial types (though I'm not sure that unbound type variable is an appropriate solution as it does not represent an invalid type), we need a way to represent partially typed AST. We need to return AST even in the error case after this change.

> PS: don't worry about not responding in some time, we all have lives! I'm also going to be absent quite a bit, I'm having 4 uni exams the next week and have to revise for them.

Good luck!!!
