### ISSUE TITLE
Allow hiding internal modules from package documentation

### ISSUE THREAD

**Issue by aslilac** [gleam-lang/gleam#1905]
If I have, say, `nakai/internal/type_that_is_not_intended_for_consumers`, which I want to be its own module to keep the code organized and idiomatic, I have to accept a couple of unfortunate things:

- This module is going to be accessible by consumers of my package
- This module is going to be shown in my public documentation

There's potentially a nice solution here that solves both together, but the documentation bit could also be solved separately

Discord conversation for reference: https://discord.com/channels/768594524158427167/768594524158427170/1055625580487377059

**Comment by lpil** [comment]
I agree, this is something we want to improve.

I think we can split this into two features in order to make it easier to tackle:
1. Omitting internal modules from documentation
2. More fine-grained privacy control (so that code can be made public only the the same package, only to a subset of a project, etc).

2 is a much larger and less clear item of work that requires more research, so I'll consider this issue to be convering 1.

Thinking about this for a while my favourite so far is to have a `documentation.hidden_modules` or similar which could be used to filter out whatever modules from the documentation.

```toml
name = "nakai"
version = "1.0.0"

[documentation]
hidden_modules = [
  "nakai/internal/*",
]
```

**Comment by lpil** [comment]
I would advise reading the documentation in the source code if you are working in the project.

**Comment by aslilac** [comment]
the use of globs immediately brings up some questions for me:

- would `nakai/internal/cool/stuff` be excluded?
- would `nakai/internal` be excluded?

and if I instead had
```
[documentation]
hidden_modules = [
  "nakai/internal",
]
```

- would that only ignore `nakai/internal` and not anything underneath it?

**Comment by lpil** [comment]
All behaviour is up for grabs!
