### ISSUE TITLE
Innacurate compiler message for missing arguments in a pipe

### ISSUE THREAD

**Issue by jiegillet** [gleam-lang/gleam#1924]
```
$ gleam --version
gleam 0.25.0
```

For this code
```gleam
[1, 2, 3]
  |> list.map()
```
the compiler message is
```
15 │     |> list.map()
   │        ^^^^^^^^^^ Expected 2 arguments, got 0
```

But since it is in a pipe, it "got" one argument, not 0.

Maybe the message should have a special case for pipes, something like "Expected 2 arguments, only got 1 from the pipe" or for larger functions "Expected 3 arguments, only got 1, plus 1 from the pipe".

**Comment by lpil** [comment]
The error is correct! Gleam's pipe is not like Elixir's in that it does not always insert the argument, it also checks to see if the right hand side of the pipe returns a function. There's no way to know which of the possible rewrites you wanted when they are all incorrect, so we arbitrarily pick one.

Here we sacrifice some clarity in the error message in order to get a much better UX with the pipe than other languages.
