### ISSUE TITLE
Order of type aliases shouldn't matter

### ISSUE THREAD

**Issue by jiegillet** [gleam-lang/gleam#1925]
```
$ gleam --version
gleam 0.25.0
```

The code
```gleam
type Bar(a) { Bar(a)  }
type Foo(a) = Map(a, Bar(a))
```
compiles, but the flipped version
```gleam
type Foo(a) = Map(a, Bar(a))
type Bar(a) { Bar(a)  }
```
doesn't:
```
19 │ type Foo(a) = Map(a, Bar(a))
   │                      ^^^^^^ Did you mean `Map`?
```

Other functions don't seem to mind the order of definition, so it feels to me like type definitions shouldn't either.

Interestingly enough, the co-recursive (although probably nonsensical)
```gleam
type Bar(a) { Bar(Foo(a))  }
type Foo(a) = Map(a, Bar(a))
```
does compile but
```gleam
type Foo(a) = Map(a, Bar(a))
type Bar(a) { Bar(Foo(a))  }
```
doesn't.

**Comment by lpil** [comment]
Sounds good! Let's sort these prior to type inference.

**Comment by asib** [comment]
Hiya, I'd be interested in tackling this if you're open to a newbie having a go? Some initial thoughts (feel free to ignore if you'd rather I don't work on this!):

The error seems to be due to the fact that the hydrator looks for the `Bar` type constructor in the environment,  but before it has been registered. High level, I can imagine a couple of approaches but I don't have a good idea of which is preferable/less complex.
- The `infer_module` function loops over statements, registering types for each. If it hits one that produces an error, it could try processing the following statement and then retry immediately after having processed that one additional statement. Could maybe be smarter about when the retry happens. This feels like not great performance, though.
- Rather than producing an error, register some sort of forward reference that can later be filled in with the actual type information, when the relevant statement is processed. I'm not sure whether this would work, as later bits of `type_from_ast` seem to depend on the actual type information fetched from the environment. However, perhaps these could be made optional and then similarly updated when the forward reference is updated?

**Comment by lpil** [comment]
That's interesting, it doesn't work for me.

![image](https://user-images.githubusercontent.com/6134406/230352456-84135292-4de8-4e98-a0df-ac02978b1e61.png)

What code did you test with?
