### ISSUE TITLE
Permit a message to be specified with `panic`

### ISSUE THREAD

**Issue by inoas** [gleam-lang/gleam#2028]
Would that be possible?

## 0.26 gleam/stdlib

```gleam
[1, 2, 3]
|> list.all(fn(x) {
  case x {
    1 -> True
    2 -> False
    // Crash if no short-circuit
    _ -> {
      assert True = False
    }
  }
})
```

## 0.27 gleam/stdlib

```gleam
[1, 2, 3]
|> list.any(fn(x) {
  case x {
    1 -> False
    2 -> True
    // Crash if no short-circuit
    _ -> panic
  }
})
```

## imaginary panic

```gleam
[1, 2, 3]
|> list.any(fn(x) {
  case x {
    1 -> False
    2 -> True
    _ -> panic("Crash if no short-circuit")
  }
})
```

```gleam
[1, 2, 3]
|> list.any(fn(x) {
  case x {
    1 -> False
    2 -> True
    _ -> panic(#("Crash if no short-circuit", x))
  }
})
```

* * *

Edit this is what we see : 
```erlang
gleam/list_test.any_test
#{function => <<"any_test">>,gleam_error => panic,line => 474,
  message => <<"panic expression evaluated">>,
```

```javascript
gleam/list_test.any_test:474: Error: panic expression evaluated
```

The panic data could replace the `message` `"panic expression evaluated"`? Maybe the panic data/message should/could only be literals, function calls should not be allowed at that point IMHO?

Ref: https://github.com/gleam-lang/gleam/issues/1961

**Comment by inoas** [comment]
Ref: https://github.com/gleam-lang/gleam/issues/1961

**Comment by lpil** [comment]
Totally! We want a custom error message for sure. I've held back on this for now because I would like `assert`, `assert let`, `todo` and `panic` to all share the same syntax for their message, and we've not found something that works for all of them yet.

If you've got any ideas for them let me know!

**Comment by Lunarmagpie** [comment]
One way to do this that would work is copying python's assert error message syntax. I don't love this but finding what doesn't work is a good step to finding what does work lol.
```gleam
let assert Ok(value) = f(), "error message"
todo, "error message"
panic, "error message"
```

**Comment by lpil** [comment]
Could also use `as`

```rust
let assert Ok(value) = f() as "error message"
todo as "error message"
panic as "error message"
```
I'm not sold with any of these syntaxes just yet, good to explore more

**Comment by greenfork** [comment]
If the message is optional, it could be

```rust
let assert Ok(value) = f()
let assert("error message") Ok(value) = f()
todo
todo("error message")
panic
panic("error message")
```

**Comment by lpil** [comment]
What would it be for bool `assert`? Here is the syntax without a message:

```python
assert x == y
```

**Comment by JohnBjrk** [comment]
I actually prefer the trailing error message, both because it sets the expression that is asserted at the center and also that if the message is optional i feels good to keep it in the end. 
I think that it might be good to keep `->` only for case expressions though (even if it looks quite neat). 
`as` looks quite ok to me.
