### ISSUE TITLE
Convert from Path to Utf8Path etc

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2079]
https://crates.io/crates/camino

**Comment by bcpeinhardt** [comment]
I'm gonna take a look at this

**Comment by bcpeinhardt** [comment]
So I've been looking at this a little bit. I think the approach I'd like to take is:
1. Change compiler-core public interfaces to all be generic over `impl AsRef<Path>` rather than taking `Path` or `PathBuf` directly
2. Change compiler-cli to use camino's `Utf8Path` and `Utf8PathBuf` for everything. 
To me this makes more sense than a dependency on camino in compiler-core.

The trade off here seems to be reduced complexity in compiler-cli for increased complexity in compiler-core (I have to figure out what to do about traits like `FileSystemReader` which are currently used as trait objects). Although tbh if I find a way to remove the use of trait objects things may get simpler, not more complicated.

Telling you all of this just so you don't think I'm ignoring it and can have some insight/chance to comment.

**Comment by bcpeinhardt** [comment]
Well idk maybe I don't mind camino in compiler-core. It doesn't actually introduce any new dependencies other than itself.
