### ISSUE TITLE
Bug report: compile error "undefined function" when calling an external function

### ISSUE THREAD

**Issue by edman** [gleam-lang/gleam#2113]
Create a new project and put the following in `src/ets.gleam` (the file name `ets.gleam` is important):

```gleam
import gleam/option.{None, Option, Some}

pub external type Ets

external fn raw_get(ets: Ets, key: String) -> List(#(String, String)) =
  "ets" "lookup"

pub fn get(ets: Ets, key: String) -> Option(String) {
  raw_get(ets, key)
  |> fix_lookup
}

fn fix_lookup(res) -> Option(String) {
  case res {
    [] -> None
    [#(_, value)] -> Some(value)
  }
}
```

Compile this and you will get an error like:

```
$ gleam build
Downloading packages
 Downloaded 2 packages in 0.05s
  Compiling gleam_stdlib
  Compiling gleeunit
  Compiling bugreport
/<Path>/bugreport/build/dev/erlang/bugreport/_gleam_artefacts/ets.erl:21:13: function lookup/2 undefined
%   21|     _pipe = lookup(Ets, Key),
%     |             ^

error: Shell command failure

There was a problem when running the shell command `escript`.
```

----

That's because the generated code should have called `ets:lookup` instead of `lookup`, as defined in the external function signature.

I notice the problem goes away if you rename the file, e.g. to `glets.gleam`, so this seems to be caused by the compiler getting symbols mixed up between my gleam `ets` module that I define in my project and the erlang `ets` module.

**Comment by lpil** [comment]
The problem here is that you have overwritten the Erlang `ets` module with your own `ets` module, so that function no longer exists. If you rename your module it'll work as desired.

This is technically outside of Gleam, but we'd like to detect when this is going to happen and emit an error. There's an issue you can track here: https://github.com/gleam-lang/gleam/issues/1267
