### ISSUE TITLE
Add live updates to path dependencies

### ISSUE THREAD

**Issue by NthTensor** [gleam-lang/gleam#2183]
Continuing work for https://github.com/gleam-lang/gleam/pull/2153.

Currently to update the source of a path dependency you must run `gleam deps update` and the source is copied into the `/build` dir. Instead, the compiler should get the source from the specified project at build time.

The right place to start is probably by moving the project-loading code into a method of `ManifestPackage`, allowing different sorts of packages to be loaded differently.

**Comment by lpil** [comment]
Currently only the top level package gets its modules checked for changes, I wanted to extend this to all packages as part of a future performance optimisation (lazy loading of cached modules). Sounds like these two goals align well, and it means we could have just a single code loading mechanism.

**Comment by NthTensor** [comment]
I was going to have a go at this next, but if you are already planning to change how modules are loaded maybe I will have a go at #1338 instead. Is there an issue for lazy loading? It sounds interesting.

**Comment by lpil** [comment]
I think this would be best to get in, mostly so that it fixes https://github.com/gleam-lang/gleam/issues/2185

There's no information on lazy loading anywhere, I tend to only do performance work once someone encounters a performance problem. The general idea is that rather than eagerly loading the cached information about a module we can note that it exists, and then load it only if it is imported by a module being compiled.

A first step for all these of these issues would be to remove [this package loading logic](
https://github.com/gleam-lang/gleam/blob/edb26e0af57f3e7411e4480c608ad328b4ad687c/compiler-core/src/build/project_compiler.rs/#L233-L236) here and to instead load dependencies per-module as the top level package is loaded.

**Comment by NthTensor** [comment]
1. Load all imported packages when compiling a module
2. Apply the existing hash-based cache invalidation to a module when it's package is loaded
   + But only do cache invalidation once per module per build
4. Compile a module when it's package is loaded and it's cache is invalid (changed or not yet built)

If that's the gist of it I think I can take a shot at it.

**Comment by lpil** [comment]
The build tool currently works like this:

```js
let dependency_packages = packages_in_dependency_order();
for (package of dependency_packages) {
  if (package.has_build_directory()) {
    load_caches(package);
  } else {
    compile_modules(package);
  }
}
compile_top_level_package();
```

We want to do this instead:

```js
let dependency_packages = packages_in_dependency_order();
for (package of dependency_packages) {
  for (module of package.modules) {
    if (module.has_valid_cache()) {
      load_cache(module);
    } else {
      compile_module(module);
    }
  }
}
compile_top_level_package();
```

**Comment by NthTensor** [comment]
Are you sure its not already doing this? To me, it looks like `ProjectCompiler::compile_dependencies` ends up calling the per-module checksum caching in `ModuleLoader::load`. Here's the call stack:

1. `ProjectCompiler::compile_dependencies`
2. `ProjectCompiler::load_cache_or_compile_package`
3. `ProjectCompiler::compile_gleam_dep_package` (assuming its a gleam dep)
4. `ProjectCompuler::compile_gleam_package`
5. `PackageCompiler::compile`
6. `PackageLoader::run`
7. `PackageLoader::read_source_files`
8. `ModuleLoader::load`
