### ISSUE TITLE
Convert conditional compilation to use attribute syntax

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2191]
Old syntax:

```rust
if erlang {
  pub fn main() { todo }
}

if javascript {
  pub fn main() { todo }
}
```

New syntax

```rust
@if(erlang)
pub fn main() { todo }

@if(javascript)
pub fn main() { todo }
```

We will also want `gleam fix` to update this syntax. https://github.com/gleam-lang/gleam/issues/2192

Prior discussion: https://github.com/gleam-lang/gleam/discussions/2133. Note this does not include the change to the external function syntax.

**Comment by lpil** [comment]
Yes, the attribute should be usable for any definition, the same as the `if` syntax can today be used for any definition.

**Comment by MarkusPettersson98** [comment]
Sorry for doing it a bit backwards this time, but I threw together [a PR](https://github.com/gleam-lang/gleam/pull/2198) which aims to implement this feature :blush: 

However, I expect it to become a bit stalled while waiting for #2192. Anyone keen on working on that? Otherwise, I could give it a shot later this week :calendar:
