### ISSUE TITLE
Improve Getting Started UX

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2350]
With v1 we may have a lot of people trying Gleam for the first time, so we want to make the experience as easy as possible.

Redesign the getting started page/flow so folks can dive right in.

**Comment by extsalt** [comment]
I've found https://laravel.com/ effective and productive. What do you think?

**Comment by lpil** [comment]
Sorry @extsalt , what about it?

**Comment by extsalt** [comment]
> Sorry @extsalt , what about it?

I'm sorry for confusion, the documentation of https://laravel.com is great. I am proposing if we could design the `getting started` for gleam as the laravel.

**Comment by Grubba27** [comment]
One thing missing for many would be a section saying _why gleam_ in the getting started.

On other parts, I would try following how [Rust does](https://www.rust-lang.org/learn/get-started) getting started:
- Running the language without installing it.
- [One small](https://www.rust-lang.org/learn/get-started#:~:text=A%20small%20Rust%20application) project that shows the powers of Gleam(maybe something with using an Erlang lib?)

Another excellent thing for beginners is showing what projects can be built with Gleam. With meteor, we have this [section](https://guide.meteor.com/#example-app) talking about [examples-repo](https://github.com/meteor/examples) that are "simple" apps but using are using our lib.

**Comment by lpil** [comment]
Definitely don't want any "why" in the getting started, that's what the homepage etc is for. "getting started" is to be optimised from going from "I want to try Gleam" to "I'm using Gleam" as quickly as possible.

**Comment by extsalt** [comment]
@Grubba27 @lpil Should I create a Figma design?, since issue is the presentation.

**Comment by lpil** [comment]
It you've some ideas that sounds great!

**Comment by chuckwondo** [comment]
@lpil, perhaps this is outside the scope of this issue and warrants a separate issue, but something that I'd like to see is how to incorporate non-gleam packages, for targeting Erlang and also for targeting JavaScript.

I'm aware of the sections in the docs on referencing external types and functions, but I'm not aware of any existing docs on how to incorporate external _packages_. For example, I'd like to use Gleam to write code that ultimately must be deployed to a Node runtime. That generally means I'll also want to make use of existing npm packages from my Gleam code, but I'm not aware of any recommendations for how to do so.

As far as I'm aware, `gleam.toml` does not support referencing npm packages as dependencies, so it's unclear how one would go about incorporating npm packages into a gleam project.

I've posted a [question in gleam discussions in this regard](https://github.com/gleam-lang/gleam/discussions/2529) (more specifically about how to structure a gleam package that has npm dependencies)

**Comment by lpil** [comment]
Gleam will not support any alternative package managers, we use Hex. If a package wants to depend on non-Hex code such as from apt or npm then they'll need to document the installation process.

**Comment by chuckwondo** [comment]
Let me reframe.

Given that gleam targets javascript, I'd like to experiment with using gleam in places where I'm currently using js/ts, but in order to be able to practically do so, I want to be able to continue using the various npm packages that my current js/ts code uses because it's impractical for me to have to write gleam ports for every npm package that I currently use, for which there is no equivalent gleam package.

Therefore, for every one of my js/ts projects that I want to convert to gleam, and that uses npm package _X_, I imagine that in order to avoid rewriting (copy-pasting) gleam ffi code for npm package _X_ within each such project I want to convert to gleam, I'll want to write and publish a gleam hex package with the ffi code that "wraps" npm package _X_, so that as I convert each project from js/ts to gleam, I can simply include the gleam hex "wrapper" package as a dependency in my `gleam.toml` file.

I am not at all familiar with hex, the structure of hex packages, nor how gleam creates hex packages for publication, so I don't know if creating such a wrapper package could or should bundle the npm package (plus transitive deps) into the hex package. I would suspect that it should _not_ bundle the npm package(s), even if it could, since that would couple each version of the hex package with a specific version of the npm package, which doesn't seem like a good idea.

If the gleam package ends up with only the ffi code, then I suspect that the js/ts projects I convert to gleam will need to have a "mixed" build process, using both gleam and npm/yarn to retrieve corresponding dependencies.

Therefore, I'm looking for advice on a reasonable approach for the following:

1. Structuring a project for writing and publishing a gleam "wrapper" for npm package _X_
2. Structuring a project written in gleam that depends on the "wrapper" gleam package and also depends on npm package _X_ that the gleam package "wraps" (ideally, incrementally converting an existing js/ts project to gleam, perhaps similar to how an existing js project can be incrementally converted to ts)

Offhand, I suspect that such a project would necessarily include both a `gleam.toml` file as well as a `package.json` file, and that the docs for the gleam "wrapper" package would indicate that it targets only javascript, and that in order to use it, you must also include the npm package _X_ (with a particular version spec) in a `package.json` file in your "mixed" project.

Generally speaking, I'm looking for guidance on a reasonable approach for a "mixed" gleam and js project where both gleam and npm packages are necessary dependencies.

**Comment by lpil** [comment]
I don't believe you will need to add any node related config or structure to the package. If the programmer knows to run `npm install xyz` beforehand then the imports will work with just that.
