### ISSUE TITLE
Rename stdlib Map type

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2405]
`Map` is a little confusing as it collides with the common map function. Let's rename it.

Keep the old module around for a few versions but make all the functions as deprecated.

What should the new name be? In discord `Dict` and `Dictionary` were popular.

**Comment by markholmes** [comment]
Given that the first line of the `gleam/map` readme says "A dictionary of keys and values", I think `Dictionary` is spot on. While I generally prefer full names, a `Dictionary` is accepted colloquially as `Dict` in computer science. 

I vote for `Dict` 🎉

**Comment by erikareads** [comment]
I think dictionaries are familiar enough concept among other programming languages to be a reasonable name for a collection.

I strongly prefer unabbreviated names. I like Gleam's value of explicitness and clarity, which I've seen in the decisions around labels and qualified imports.

The `as` keyword gives the opportunity for the level of abbreviation relevant to a given module:

```gleam
import gleam/dictionary as dict
import gleam/dictionary as d
```

(I'm also in favor of `integer` and `boolean` instead of `int` and `bool` for consistency and clarity.)

I vote for `dictionary`.

**Comment by matt-savvy** [comment]
If it's gonna change, I would vote for `Dict` / `dict`.

**Comment by abs0luty** [comment]
I don't think `dict` is not explicit enough, but I personally prefer unabbreviated names, so I vote for `Dictionary`.

**Comment by inoas** [comment]
For the built-in types and modules I am a fan of Bool, Int etc. but for anything beyond the basic types I like unabbreviated names.

This is also nicer for newbies that might wonder what dict could mean, there dictionary might be confusing enough.

However personally i'd keep it to be Map/map and if it feels like a must have rather rename the map functions. Map is what will people will look for, experienced and possibly even newbies.

**Comment by edkelly303** [comment]
In terms of what people will look for, I think it depends which other languages you know. Map is not an obvious name if your previous languages are Python or Elm, but Dictionary or Dict would be.

I prefer Dict to Dictionary, because I'm a lazy typist and I don't think the explicitness of the longer name is useful. Calling it a dictionary is just a metaphor anyway, and potentially a misleading one for a user who doesn't already know its semantics (are entries ordered alphabetically by key, like a paper dictionary, or does it use insertion order, or something else?)

Leftfield suggestion: what about KeyValue or KeyVal or KV?

**Comment by abs0luty** [comment]
> Leftfield suggestion: what about KeyValue or KeyVal or KV?

I think the name is a little bit confusing. It might be confused with just a single key value pair (maybe tuple), idk.
