### ISSUE TITLE
Inexhaustive warning message is incorrect for case expressions with multiple subjects

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2426]
```
warning: Inexhaustive patterns
  ┌─ /src/warning/wrn.gleam:3:3
  │  
3 │ ╭   case x, y {
4 │ │     True, _ -> 1
5 │ │   }
  │ ╰───^

This case expression does not have a pattern for all possible values.
If is run on one of the values without a pattern then it will crash.

The missing patterns are:

    False
```

The missing pattern should be `False, _`. The fact there are multiple patterns has been lost.

**Comment by TanklesXL** [comment]
Heya @lpil , this may or may not be related to the following warning I got with exhaustiveness and guards. Given the following snippet:

```gleam
  case 1 {
    x if x < 0 -> panic
    x if x > 0 -> panic
    x if x == 0 -> panic
  }
```

Even though a given integer must be either greater, equal to or lower than 0, I get an exhaustiveness warning.

```text
warning: Inexhaustive patterns
  ┌─ .../code/gleam/exhaust/src/exhaust.gleam:4:3
  │  
4 │ ╭   case 1 {
5 │ │     x if x < 0 -> panic
6 │ │     x if x > 0 -> panic
7 │ │     x if x == 0 -> panic
8 │ │   }
  │ ╰───^

This case expression does not have a pattern for all possible values.
If is run on one of the values without a pattern then it will crash.

The missing patterns are:

    _

In a future version of Gleam this will become a compile error.
```

Maybe I'm misunderstanding how the exhaustiveness checking currently works and this is totally fine though, it just seemed a bit odd to me 😄

**Comment by michallepicki** [comment]
An interesting example:
```gleam
import gleam/io

pub fn main() {
  let x = False
  let y = True
  case x, y {
    True, True -> 1
  }
}
```

The error is:
```
warning: Inexhaustive patterns
  ┌─ /src/main.gleam:6:3
  │  
6 │ ╭   case x, y {
7 │ │     True, True -> 1
8 │ │   }
  │ ╰───^

This case expression does not have a pattern for all possible values.
If is run on one of the values without a pattern then it will crash.

The missing patterns are:

    False
    True

In a future version of Gleam this will become a compile error.
```

**Comment by michallepicki** [comment]
Copying my notes from Discord to here:

I think it's possibly a mistake that for a multi-pattern the compiler just [inserts multiple columns directly](https://github.com/gleam-lang/gleam/blob/d54068759154f0cc9fd88f67844880607559ac5c/compiler-core/src/type_/expression.rs#L2492) without wrapping them in anything
In presence of multi-patterns, the first decision created should be a Switch with one Case (like it is for tuples or patterns for custom types with one constructor), or some new dedicated one that works the same way, and then when traversing the tree to print missing patterns it could be [handled similarly to a tuple](https://github.com/gleam-lang/gleam/blob/d54068759154f0cc9fd88f67844880607559ac5c/compiler-core/src/exhaustiveness/missing_patterns.rs#L178)

The columns seem like an internal thing of the exh checking and because of the recursive nature of the algorithm, it's not easy to detect the outermost one for multi-patterns to special-case it when compiling rows. So I would propose to either
- insert one column, have dedicated data types for handling multi-patterns
- insert one column using the same data types as a tuple does, but with some flag designating that it's a multi-pattern so that missing patterns get printed correctly
- continue inserting multiple columns, but in Compiler::compile don't call the recursive compile_rows directly, but first call some function that will handle the presence of multiple outermost columns to create a Switch decision or equivalent [somewhere around here](https://github.com/gleam-lang/gleam/blob/d54068759154f0cc9fd88f67844880607559ac5c/compiler-core/src/exhaustiveness.rs#L257) (still some changes to data types will be needed to handle printing of missing multi-patterns) - but also I'm not yet clear on how guards are handled, so maybe this is not an option

**Comment by quadroli** [comment]
Helloo 👋 also related, I think there is a grammartical error in the message: If is run should be: if _it_ is run

**Comment by lpil** [comment]
Thank you
