### ISSUE TITLE
Precompile wasm version and attach to release

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2433]

**Comment by fffnite** [comment]
Am I right in saying this issue is to get a target added to the `release.yaml` workflow to build the wasm version of the compiler? 

If so, is there any existing docs on building the wasm target of this project? didn't spot much in the Makefile or any such ^^; happy to just try take a stab at it though even if there's not too much existing docs :).

**Comment by lpil** [comment]
That's right! The README has some instructions
