### ISSUE TITLE
✨ Introduce an `@internal` attribute for individual declarations.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [gleam-lang/gleam#2486]
## Background

Currently we have the `internal_modules` entry in our `gleam.toml` as a way of excluding certain modules from the generated documentation. Any `pub` code is always importable, but by excluding it from the docs it is de facto internal and not part of the public API.

This solution works well when you have large chunks of internal functionality, but quickly gets clunky when you have small bits of internal functionality next to public code.

It is good practice to define custom types as `pub opaque` unless there is good reason to do otherwise: this means consumers can't pattern match on your custom types and the implementation details remain hidden. Because of this though, it is not possible to have a `pub opaque` type part of the public API and a separate internal module that can pattern match on that type.

## Propsal

I'm proposing an `@internal` attribute that can be attached to declarations that hides that declaration from the generated documentation in an otherwise-public module:

```gleam
pub opaque type Wibble {
  Wibble
  Wobble
}

@internal 
pub fn encode(wibbble: Wibble) -> Json {
  case wibble {
    Wibble -> ...
    Wobble -> ...
  }
} 
```

Here this `encode` function needs access to the structure of the `Wibble` type in order to encode it to JSON properly, but the function itself is not part of the public API. This is handy if we have other parts of a package that might need to know how to encode a Wibble.

---

## Prior art

Elixir has this functionality by setting `@doc false`, see [here](https://hexdocs.pm/elixir/1.12/writing-documentation.html#hiding-internal-modules-and-functions)

**Comment by lpil** [comment]
Seems reasonable to me. We will see if anyone has any thoughts or adjustments or objections.

It should also be excluded from autocompletions from other packages.

**Comment by massivefermion** [comment]
Makes sense to me. Gonna keep my eye on this issue and start working on it when it's final.

**Comment by erikareads** [comment]
I could use this too, I like the current `@internal` proposal.

**Comment by cauebs** [comment]
Won't this be a little bit confusing? First, because it seems somewhat symmetric to `@external` while having nothing to do with it. Second, because then you can have some marked as `pub` that isn't exactly public? Users would then be able to use items that are not documented. Are breaking changes to these items allowed without affecting semver?

Looking at Rust for alternative ideas, there are two things that I understand would satisfy the current proposal's goals: there's the `#[doc(hidden)]` attribute, and there's the `pub(crate)` visibility modifier, both reasonably self-explanatory.

Couldn't we go one of these ways?

**Comment by massivefermion** [comment]
@cauebs brings up a very good point. It can't be `@internal`. Maybe `@hidden`? or `@no_doc`? something like that!

**Comment by erikareads** [comment]
We already have a notion of `internal` that works this way:

```toml
# Modules that should be considered "internal" and will not be included in
# generated documentation. Note this currently only affects documentation;
# public types and functions defined in these modules are still public.
#
# Items in this list are "globs" that are matched against module names. See:
# https://docs.rs/glob/latest/glob/struct.Pattern.html
#
# The default value is as below, with the `name` of your project substituted in
# place of "my_app".
internal_modules = [
  "my_app/internal",
  "my_app/internal/*",
]
```

Having public functions that aren't visible is useful for FFI and Testing.

Having an `@library` or something that matches `pub(crate)` would be a stronger guarantee for what I need, but that will likely require more significant work.

**Comment by lpil** [comment]
> Won't this be a little bit confusing? First, because it seems somewhat symmetric to @external while having nothing to do with it. 

It hasn't come up yet with internal modules, but I can see what you mean. We could rename them both to something else if we have a better name.

> Second, because then you can have something marked as pub that isn't exactly public? Users would then be able to use items that are not documented.

Aye, that's the goal of the feature. It's a statement about the contract between the user and this program.

> Are breaking changes to these items allowed without affecting semver?

They would be, aye.

**Comment by erikareads** [comment]
```
hidden_modules = [...]
```

```rust
@hidden
pub type HiddenThing
```

**Comment by lpil** [comment]
I'm not a huge fan of hidden as I think that name describes a consequence of what they are, but not what they are. The contract of them being externally private is far more important than them being hidden from documentation.

**Comment by massivefermion** [comment]
What about `@private`?

**Comment by massivefermion** [comment]
`@restricted`, `@reserved`, `@exclusive`?

**Comment by lpil** [comment]
Perhaps `@unsupported` ?

**Comment by lpil** [comment]
You say that, but I don't know what any of those three words mean in this context. They're not restricted or reserved in any way, and I'm not sure what they're exclusive of.

I find `@unsupported` and `@internal` more clear as they're functions for which support is not provided if you use them due to their being internal to the package itself.

**Comment by massivefermion** [comment]
my bad! Although I still don't see `@unsupported` implying what we mean here. Just to make myself clear, from the perspective of the user of the package, using the definition from that package is unsupported, but from the perspective of the author, it doesn't make sense, what is it that is not supported?! I just don't see it.
Sorry, I think I'm starting to ramble again, last words, I'm now more on the side of hayleigh's `@internal`.

**Comment by hayleigh-dot-dev** [comment]
Remember that the purpose of this annotation is to _hide a declaration from the generated docs_. That means anyone who sees this annotation is necessarily looking at the source code! That means they are beyond the realms of a normal package consumer, and are now someone,, looking at the internals! 

From _that_ perspective, it becomes immediately valuable to see a `pub` declaration with an `@internal` attribute because its telling you - non-author snooping at the source - that this particular function is for internal use and you should use at your own risk. 

I think I've convinced myself further that `@internal` is the right word.

---

Unrelatedly, to add more support to this issue in general. It would be nice to be able to mark the `main` function of a module as internal too. I always find it very odd when I'm looking at package docs with a `main` just hanging out.

**Comment by cdaringe** [comment]
we have `pub type Foo`, but we could also entertain rust type `pub (module) type Foo` for scoped public-ness.

in this respect, i could put my `pub (module) opaque type` in internal/*, and because it's a `pub (module) ...`, it's permitted to be consumed in my module.

i may not be grokking the proposal perfectly, but I _prefer_ something like the rust strategy over `@internal`. in the example above, `encode` was decorated with `@internal` to work around an issue with `Wibble`. my intuition suggests that fixing the scoping with `Wibble` can and should be handled at `Wibble`, rather than by _consumers_ of `Wibble`.

🤔

**Comment by giacomocavalieri** [comment]
I agree with Hayleigh and `@internal` also feels very natural once someone is also exposed to the idea of _internal_ modules: the annotation basically does the same thing but on a per-definition basis instead of being applied to a whole module.
That's something I felt I could use a couple of times: "it would be really nice to hide this function from the public API but I don't want (or I can't) move this to an internal module", to which a natural answer is "make it an internal definition!"

Also to add to the issue, we would need to warn if any type marked as @internal is inadvertently exposed in the public api (just like suggested here #2234)

**Comment by lpil** [comment]
@cdaringe This is similar but not the same as making an item public for a package or set of modules.

I would also be interested in a system for drawing lines within a package to enforce certain relationships between subsystems, but we don't have a good design yet. Rust's system is capable but I've never seen anyone do more than `pub(crate)`, which makes me think it's not a good design- it doesn't matter if it's capable of doing something if no one wants to use it.

**Comment by giacomocavalieri** [comment]
I think this can be closed now 🥳

**Comment by lpil** [comment]
Thank you!!
