### ISSUE TITLE
Cannot find imported type DecodeError

### ISSUE THREAD

**Issue by keroami** [gleam-lang/gleam#2514]
```
$ gleam new problem
$ cd problem
$ gleam add gleam_stdlib
```
then edit `src/debug.gleam` to contain
```gleam
import gleam/dynamic.{type Dynamic, DecodeError} as d

pub fn decode(instance_state: Dynamic) -> Result(Int, DecodeError) {
  d.int(instance_state)
}
```
then 
```
$ gleam build
  Compiling problem
error: Unknown type
  ┌─ /tmp/problem/src/debug.gleam:3:55
  │
3 │ pub fn decode(instance_state: Dynamic) -> Result(Int, DecodeError) {
  │                                                       ^^^^^^^^^^^ Did you mean `BitArray`?

The type `DecodeError` is not defined or imported in this module.

```
gleam of main branch (hash 23ef49c7)
fresh version of stdlib (0.34.0)

**Comment by keroami** [comment]
never mind, need `type DecodeError`

**Comment by keroami** [comment]
not a problem

**Comment by giacomocavalieri** [comment]
The problem here is that you've imported the _constructor_ `DecodeError` and not the type `DecodeError`, changing the import the code starts compiling again:
```diff
- import gleam/dynamic.{type Dynamic, DecodeError} as d
+ import gleam/dynamic.{type Dynamic, type DecodeError} as d
```

The error message could be more useful though I can see this being a common problem if the module exposes a constructor and type with the same name.

An idea on how it could work: when the compiler runs into an undefined type it could see if there's an imported constructor with that name and if the module its imported from exposes a type with the same name it could suggest importing that as well.

The error message could then look something like this:
```text
error: Unknown type
  ┌─ /tmp/problem/src/debug.gleam:3:66
  │
3 │ pub fn decode(instance_state: Dynamic) -> Result(List(Int), List(DecodeError)) {
  │                                                                  ^^^^^^^^^^^

Hint: Maybe you wanted to import `type DecodeError` from the `gleam/dynamic` module?
```

Or it could be even more specific and go into more detail explaining the difference between importing a constructor and a type, that would be quite useful and friendly to newcomers who may make the same error
