### ISSUE TITLE
Fatal Compiler Bug: Unexpected pattern

### ISSUE THREAD

**Issue by markholmes** [gleam-lang/gleam#2577]
I ran into a compiler error while building a Wisp app and using `gleam_pgo`. This might be user error, but I figured I'd share it.

```
➜ app (main) ✗ gleam run
  Compiling app
error: Fatal compiler bug!

This is a bug in the Gleam compiler, sorry!

Please report this crash to https://github.com/gleam-lang/gleam/issues/new
with this information and the code that produces the crash.

    compiler-core/src/exhaustiveness.rs:431
    Unexpected pattern Tuple { elements: [Id { idx: 2 }, Id { idx: 3 }] }
```

```rust
fn get_person(ctx: Context, id: String) -> Response {
  let sql =
    "
    SELECT name, email
    FROM users
    WHERE id = $1
  "

  // Parse the :id query parameter
  let assert Ok(user_id) = int.parse(id)

  // Define a dynamic tuple for the returned sql value
  let user = dynamic.tuple2(dynamic.string, dynamic.string)

  // Execute the sql query
  let result = pgo.execute(sql, ctx.db, [pgo.int(user_id)], user)

  case result {
    Ok(user) -> create_user_response(user)
    _ -> wisp.not_found()
  }
}

// The `case result` above determines that user is of type `Returned(#(String, String))`
fn create_user_response(user: Returned(#(String, String))) -> Response {
  // This would be no problem:
  // let Returned(_, user) = user

  // This is a compiler bug:
  let Returned(_, [#(name, email)]) = user

  // Return any response
  wisp.not_found()
}
```

I can try to create a repository to reproduce this if needed, but the `get_person` function is basically replacing the [`read_person`](https://github.com/gleam-wisp/wisp/blob/main/examples/5-using-a-database/src/app/web/people.gleam#L85) function from the "Using a database" example in the Wisp documentation, except that I brought in `gleam_pgo`.

**Comment by lpil** [comment]
Thank you

**Comment by giacomocavalieri** [comment]
I've done some looking around and narrowed this down a bit if it can be of any help.
So a test that is producing the same crash is this one:
```rust
#[test]
fn this_crashes() {
    assert_warning!(
        r#"
pub type Returned(a) {
  Returned(List(a))
}

fn foo(user: Returned(#())) -> Int {
  let Returned([#()]) = user
  1
}
"#
    );
}
```
You don't get a crash if `Returned` doesn't have a generic (for example if you say its constructor is a fixed `Returned(List(#()))`)

The problem is that, when doing the exhaustiveness checking, it ends up running into a type variable (the `Returned` one) and `branch_mode` decides that is `Infinite` and the you run into the tuple pattern and get the crash.

Funnily enough, if you remove the list and just do:
```gleam
pub type Returned(a) {
  Returned(a)
}

fn foo(user: Returned(#())) -> Int {
  let Returned(#()) = user
  1
}
```
You don't get the crash anymore, so I'm guessing it might have to do with how list patterns are handled. I'm not really familiar with the algorithm so I could actually fix the bug but maybe this can be of help

(Huge thanks to @danielSherlock for helping me out!)

**Comment by lpil** [comment]
Oops! Found another bug
