### ISSUE TITLE
Proposal: Make the compiler in gleam

### ISSUE THREAD

**Issue by Sxmourai** [gleam-lang/gleam#2663]
It would be great to have the whole compiler made in gleam instead of rust

**Comment by Willyboar** [comment]
Hello! This is something that's been discussed a lot. There is no benefit from doing that because demand a lot of working hours and gleam core team is small. This will hold back gleam from improving the language itself and the ecosystem generally. Imo bootstrapping a language is something must be done in early stages and surely not after 1.0 releases. 

Although there are already existing a lexer and a parser for gleam language written in gleam language.

**Comment by lpil** [comment]
Yup! Better to spend 2 years improving Gleam than to spend 2 years getting back to where we are today!

**Comment by Sxmourai** [comment]
Yes no problem ! I totally understand... I just tought It could be a reminder for like in 2+ years
________________________________
De : Louis Pilfold ***@***.***>
Envoyé : lundi 11 mars 2024 11:15
À : gleam-lang/gleam ***@***.***>
Cc : Sxmourai ***@***.***>; Author ***@***.***>
Objet : Re: [gleam-lang/gleam] Proposal: Make the compiler in gleam (Issue #2663)


Yup! Better to spend 2 years improving Gleam than to spend 2 years getting back to where we are today!
