### ISSUE TITLE
Use of the p5js JavaScript library in Gleam

### ISSUE THREAD

**Issue by SoerenSofke** [gleam-lang/gleam#2779]
Dear all,

I am happy to see a new star rising in the realm of practical functional programming languages :-).

Since I want to explore Gleam's capabilities in the context of creative coding for the browser using p5js [1], I need to load the p5js library using the @external attribute. However, I cannot figure out how to do this correctly and any help would be appreciated. p5js seems a bit special, and my JavaScript knowledge is limited.

Thank you for your support,
 Sören

[1] https://p5js.org/

**Comment by Acepie** [comment]
P5js can be a bit weird/obtuse to work with since its really designed to be used with its editor/in its own environment. I created a sample project showcasing an mvp of how you can do the bindings and render a web page https://github.com/Acepie/p5js_gleam I ultimately made a light wrapper framework around their class so that I could call out to p5js while still keeping in the functional spirit. I made the minimal bindings with a script but you could add more/use this as an example for your own needs

**Comment by SoerenSofke** [comment]
Dear @Acepie, 

Thank you very much for the initiative and the effort you have made to implement a binding in the example :-). I will try it out and contact you if I have any questions.

Best, Sören

**Comment by lpil** [comment]
This is super cool!! If you decide to make a package for this let me know, I'd love to play about with this.
