### ISSUE TITLE
Formatter | Ignore specific files

### ISSUE THREAD

**Issue by ghivert** [gleam-lang/gleam#2787]
Hi and thanks for the hard work!

Being used to Prettier in JS world, I think it's valuable to have the option to ignore the formatting of a file or of a block.
In Prettier, it's doable by adding a comment `// prettier-ignore` in the file or just before the block to format.

What do you think of such an inclusion for Gleam? I feel like it's better when you have a long list of one-liner function in a Gleam file instead of having all the line jumps for example.

**Comment by giacomocavalieri** [comment]
Hello thank you for your feedback! Gleam's formatter has no configuration and no way of being disabled by design. This we can make sure that all projects have a consistent and familiar style, no matter who wrote it.

Could you show an example of the piece of code where you'd improve the default behavior? Maybe the formatter's behavior could be improved in that case :)

**Comment by lpil** [comment]
Thanks both!
