### ISSUE TITLE
Make it possible for analysis to return multiple errors for a single module

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#2951]
Return a data structure of typed code, warnings, and errors. If there are errors then the build is a failure and codegen is expected not to happen.

This ticket does not need to include making all the analysis code actually return multiple errors, this is just a first step to get the mechanisms in place.

**Comment by Acepie** [comment]
I had some time and wanted to PoC this piece out. I think I got enough of the plumbing to show that we can accumulate multiple errors and display them but I don't think we'll be able to proceed past the first failing module until we have type holes and can guarantee a module can get created. That being said, I was able to use private type leaking as a test case to show that the plumbing works at least and that the compiler is finding and returning multiple errors when it can (since type leaks don't actually effect the final types it seemed like a good case to test that was always safe to continue)

<img width="1512" alt="Screenshot 2024-04-11 at 6 55 51 AM" src="https://github.com/gleam-lang/gleam/assets/5996838/76d39b8c-39fe-470a-9464-76aa92e8d412">
<img width="1190" alt="Screenshot 2024-04-11 at 6 56 18 AM" src="https://github.com/gleam-lang/gleam/assets/5996838/3d8d026c-070e-45ed-ba8d-23738009fff5">

I'm gonna raise a draft pr for now and think it over a bit more

**Comment by lpil** [comment]
Awesome!! Thank you

>  I don't think we'll be able to proceed past the first failing module until we have type holes and can guarantee a module can get created.

Could you expand upon this? We do have type holes and when there's an error there's no guarantee that a module can be codegen'd. I think I'm misunderstanding. 😅

**Comment by lpil** [comment]
Oh yes sorry! I misread that as "first function" and not "first module" 😅 

Yup I would like to stop at the first module 👍
