### ISSUE TITLE
Formatter: make long functions in type annotations easier to read

### ISSUE THREAD

**Issue by jfmengels** [gleam-lang/gleam#2988]
In the following function, I find it hard to read the type for `get_visitor`, especially that `get_visitor` is a function.

```gleam
fn apply_visitor(
  a: a,
  rules: List(rule.ModuleVisitorOperations),
  get_visitor: fn(rule.ModuleVisitorOperations) ->
    option.Option(fn(a) -> rule.ModuleVisitorOperations),
) -> rule.ModuleVisitorOperations {
  todo
}
```

My suggestion:

```gleam
fn apply_visitor(
  a: a,
  rules: List(rule.ModuleVisitorOperations),
  get_visitor:
    fn(rule.ModuleVisitorOperations) -> // arrow either here, or on the next line (à la elm-format)
       option.Option(fn(a) -> rule.ModuleVisitorOperations),
) -> rule.ModuleVisitorOperations {
  todo
}
```

**Comment by lpil** [comment]
I'm not so sure about this one- I don't find it any easier to read. Could it be this is what you are familiar with rather than it being better?

Would this also apply to let and use and other annotations rather than just functions? Currently we are consistent everywhere with this formatting.

Interested in hearing what others have to say.

**Comment by han-tyumi** [comment]
I find with the proposed change that the function type is more "together" as you would expect to see it if it were on its own.

I don't think it's a _huge_ difference, but I do find the extra whitespace makes it a bit easier to read the whole function type.
