### ISSUE TITLE
Incorrect Diagnostic given sometimes when naming type

### ISSUE THREAD

**Issue by u9g** [gleam-lang/gleam#2998]
As seen in the screenshot, the compiler gives the diagnostic that "names" should start with lowercase letters despite this being a type name, which should give the second diagnostic shown.

![image](https://github.com/gleam-lang/language-tour/assets/43508353/7bb7754a-df95-43b3-891d-c27f1f1bc634)

![image](https://github.com/gleam-lang/language-tour/assets/43508353/12aee1c3-066e-4ef1-89a8-259598ebd13d)

**Comment by lpil** [comment]
Oops. Thank you!

**Comment by Acepie** [comment]
Looks like the difference between the two is that the first one errors earlier as a lexer error before even getting to the parser for the compiler to figure out if it expected a value name or a type name. We could either change the error message to be applicable to either or we could somehow switch the lexer to accept this and move the error forward to the parser.

FWIW you can also get the opposite error (expected a value name but user started with an uppercase and gets a lex error) for the same reason as shown in the screenshot below. 

<img width="1512" alt="Screenshot 2024-04-18 at 6 22 40 PM" src="https://github.com/gleam-lang/gleam/assets/5996838/bf59931d-bb1e-49f0-94cc-661624e6dfd9">

Changing the error message is definitely the easier/less error prone option since I think the alternative would probably require lexing both as a single token type and disambiguating in the parser but not sure if the user experience would actually be better (i.e would we be better off just having a single bad name message that mentions both the type and value constraints)

**Comment by Acepie** [comment]
Alternatively instead of immediately returning a lex error for these cases we make a new token type for a generic bad name and continue lexing so that the parser can decide which one it wanted

**Comment by lpil** [comment]
We're talking about relaxing the parsing of lowercase names and turning them into an error in analysis in order to enable the formatter to auto-correct function names. That would enable us to give error messages with more context here too if we decide to do that.

https://github.com/gleam-lang/gleam/issues/2978

**Comment by Arian94** [comment]
The thing I can think of is that in this language the naming convention is determined by its previous token (```let```, ```type``` etc.) so THIS should be the controlling factor in the ```lex_name()``` implementation but one can see that **the name** itself is being examined in order to give proper corrections. That's the real issue and a refactor might be needed.

**Comment by GearsDatapacks** [comment]
Just realised this issue can be closed now due to #2978

**Comment by lpil** [comment]
Thank you!
