### ISSUE TITLE
Jot tests fail on JavaScript

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#3195]
I have not investigated yet but seeing as it's pure Gleam it means there's some bug in the compiler or the standard library causing it here.

https://github.com/lpil/jot

**Comment by BradLewis** [comment]
So I had a look into this, and it looks like this is due to the difference in behaviour between the `string.split_right` implementation between erlang and javascript. The test in question uses unicode spaces, and the erlang implementation will keep the space, whereas the javascript version will strip it. 

The relevant code is in the following function:
```gleam
// jot.gleam
fn inlines_to_html(html: String, inlines: List(Inline), refs: Refs) -> String {
  case inlines {
    [] -> html
    [inline, ..rest] -> {
      html
      |> inline_to_html(inline, refs)
      |> inlines_to_html(rest, refs)
      |> string.trim_right
    }
  }
}
```
If we look at the bad test, with javascript we go from
```
"<p><em> a "
to
"<p><em> a"
```
whereas in erlang we keep the space.

I'm not sure what the desired behaviour is here though in order to fix it.

**Comment by lpil** [comment]
Good detective work! That is a rather annoying difference. 🤔

**Comment by BradLewis** [comment]
Yeah definitely not ideal. I'm not sure how/if we would want to resolve this difference. Is there precedence elsewhere in the standard library where there is/was different behaviour between JS and Erlang?

**Comment by lpil** [comment]
We want them to behave the same here.

**Comment by BradLewis** [comment]
In that case I have created a PR to rework the javascript behaviour to match the erlang behaviour.
