### ISSUE TITLE
add Option Type to Preluded features

### ISSUE THREAD

**Issue by jpx40** [gleam-lang/gleam#3213]
Hey, think it would improve readability and ease of use if the Option Type would be preluded like Result. And option.unwrap_or like Rust would be cool, option.or and option.lazy_or already exist but both take an Option it would be nice if would take an normal generic. And i don't if option.unwrap would be useful maybe not most useful function i came from Rust and think about what gleam is missing this would make it easier for me to use the Option type.

**Comment by lpil** [comment]
Hello! We don't move types to the prelude unless there is something that could not be implemented in userland, so option will not be promoted.

[Option isn't used very much in Gleam compared to Rust](https://hexdocs.pm/gleam_stdlib/gleam/option.html#Option) so there's not much reason to add these methods, especially since it might give the wrong impression that you should use it in places where Gleam uses Result.

**Comment by jpx40** [comment]
> Hello! We don't move types to the prelude unless there is something that could not be implemented in userland, so option will not be promoted.
> 
> [Option isn't used very much in Gleam compared to Rust](https://hexdocs.pm/gleam_stdlib/gleam/option.html#Option) so there's not much reason to add these methods, especially since it might give the wrong impression that you should use it in places where Gleam uses Result.

ok, thanks for quick reply, i had a vision from Rust for it, since i used Option a lot especially when i worked with TOML or json.
