### ISSUE TITLE
Surface diagnostic errors for import cycles

### ISSUE THREAD

**Issue by TanklesXL** [gleam-lang/gleam#3274]
It would be helpful to surface some/all of the import statements causing an import cycle via a diagnostic error. This way the editor does not appear to have started failing to report all diagnostic data from the gleam build tool.

Currently import cycles result in compilation errors like the following:

```
error: Import cycle

The import statements for these modules form a cycle:

    ┌─────┐
    │     thing3
    │     ↓
    │     thing2
    │     ↓
    │     thing
    └─────┘
Gleam doesn't support dependency cycles like these, please break the
cycle to continue.
```

In some editors (nvim, vscode) this error is logged with a popup but results in no other editor response, in zed there is no popup for this output 

It may also be useful for the compiler message to include the code locations of the imports involved

**Comment by TanklesXL** [comment]
cc @Acepie to make it easier for you to find this

**Comment by lpil** [comment]
Isn't this a Zed bug?

**Comment by Acepie** [comment]
This is partially a zed/editor bug/weird behavior since it is not nicely showing the diagnostic if it has no location. That being said, since we know where the imports are occurring, we can attach location data here which would improve the experience regardless since even in the editors where it does show, it doesn't render in a way that is helpful/easily understandable

![image](https://github.com/gleam-lang/gleam/assets/5996838/dfbf4e2d-5ecb-475c-8169-d9064b437ac0)

**Comment by lpil** [comment]
I suppose we could identify the module with the newest mtime and put the diagnostic there?

**Comment by Acepie** [comment]
I wanna see if it's possible to put it on all of them but starting with the one we find that causes the cycle or the newest one would be good. There may be a separate thing to think over on how we write errors knowing that editors handle locationless diagnostics like this

**Comment by lpil** [comment]
Putting it on all of them would be the easiest I wager.

**Comment by Acepie** [comment]
![Screenshot 2024-06-13 210045](https://github.com/gleam-lang/gleam/assets/5996838/c0676bb2-2af4-440f-b396-e32617dc8e1d)

![Screenshot 2024-06-13 210758](https://github.com/gleam-lang/gleam/assets/5996838/6842a3a7-8ba6-4edc-9fcb-98a95009cde5)

This ended up being a slightly heavier lift than i originally realized since it turned out we were never actually rendering extra_labels to the lsp and we have not had cross file error labels before. Here's what the new changes look like if we do render these out to the lsp. I think this seems like a nice improvement but lmk if this looks too noisy

**Comment by TanklesXL** [comment]
Great work y'all!

**Comment by osiewicz** [comment]
Hey! Zed developer here,
AFAICT we implement support for `ShowMessageRequest`, but not the `ShowMessage` (notification); it looks like Gleam language server uses the notification, which is where things go sideways (https://github.com/gleam-lang/gleam/blob/bcb9c719286a204fe1f91c870d92490ef2570a38/compiler-core/src/language_server/server.rs#L217).

The fix obviously lies on our side; Once we implement support for `ShowMessage` notifications, the import cycle messages will be shown in a toast notification.
