### ISSUE TITLE
LSP: Suggestion on record accessors 

### ISSUE THREAD

**Issue by gusinacio** [gleam-lang/gleam#3298]
Given the following record:
```gleam
pub type Model {
  Model(count: Int, cats: List(String))
}
```
I'd like to be able to auto-complete the accessors:
```gleam
let model = Model(0, [])
model. // <- should suggest `count` and `cats`
```

**Comment by lpil** [comment]
This is planned for sure! I don't think we have an issue to track it though, so let's use this one. Thank you

**Comment by GearsDatapacks** [comment]
I'm going to give this one a shot

**Comment by Acepie** [comment]
I have something working in local for this at a basic level but we'll probably wanna improve the fault tolerance granularity aside from this to make it more usable

**Comment by Acepie** [comment]
I put the initial implementation up for review. It works well in basic cases like if the record access is the only error in an expression (like if its passed to a pipe or the last argument of a function) but we will wanna improve this with better function call fault tolerance. In addition, because only typing `record.` is a parse error, users will need to type at least 1 character to get suggestions
![Screenshot 2024-07-05 070058](https://github.com/gleam-lang/gleam/assets/5996838/54e18cc4-ffb1-448f-8e73-05dc6652baef)
![Screenshot 2024-07-05 065947](https://github.com/gleam-lang/gleam/assets/5996838/66632f26-932b-4b0a-9136-f8bdb38a2686)

**Comment by lpil** [comment]
> because only typing record. is a parse error, users will need to type at least 1 character to get suggestions

How about we make it parse an empty sting label in that case and then reject it in the analyser?

**Comment by Acepie** [comment]
Yeah that sounds reasonable to me :D let me add that

**Comment by Acepie** [comment]
There are still a couple interesting edge cases where we don't give a suggestion but overall that worked/improves things (since the parser ignores whitespace if the next line has a valid record constructor you'll get a correct but surprising record constructor in the ast instead of a field access resulting in no suggestions)
