### ISSUE TITLE
LSP: Show auto-complete types instead of the module names

### ISSUE THREAD

**Issue by Zhomart** [gleam-lang/gleam#3323]
Gleam: 
<img width="572" alt="image" src="https://github.com/gleam-lang/gleam/assets/830536/40cac882-f8d8-4373-96f1-662e67c11833">

How other languages do:

Rust: 
![image](https://github.com/gleam-lang/gleam/assets/830536/e955d6bb-09a4-4211-98f3-bca3c9f75002)

Typescript (only on select):
<img width="733" alt="image" src="https://github.com/gleam-lang/gleam/assets/830536/b5af248e-0474-404b-997d-bae4bc575539">

Golang (only on select):
<img width="579" alt="image" src="https://github.com/gleam-lang/gleam/assets/830536/be483fa3-d948-413c-894b-e99ada3afa60">

I've created a PR to showcase this (https://github.com/gleam-lang/gleam/pull/3322), what do you think?

**Comment by lpil** [comment]
The examples you've given here don't support removing the module in my eyes.

Rust: it prominently shows the module first of all. When there is not enough space for the module and the type it shows only the module.

TypeScript: The module is used in the code to filter the suggestions so they all belong to the same module. In this case it is safe to only show the type.

Go: This is completion on an object rather than generally so no modules are included.

It is vital that there is a way for the programmer to be able to tell what module each item comes from. Today we show both the module and the type, with the type being in the further details section, which you have collapsed in VSCode so it does not show. We could adopt the Rust approach where it shows the type information inline in the instance there is enough space after the module, or we could take some other approach so long as the module is always clear.

**Comment by Zhomart** [comment]
I believe gleam should show type information. This helps engineers during coding.

It seems like we can use field to show type informaiton.  Let me try create PR and see if it works.

<img width="646" alt="image" src="https://github.com/gleam-lang/gleam/assets/830536/3b1fc8d7-c5ca-4d0e-a5f3-df98070b0973">

**Comment by Zhomart** [comment]
Hi @lpil, please take a look at this (https://github.com/gleam-lang/gleam/pull/3364) example. VSCode shows it nicely. What do you think?

**Comment by lpil** [comment]
Hello! Please reply to my comments above 🙏

**Comment by Zhomart** [comment]
> The examples you've given here don't support removing the module in my eyes.
> 
> Rust: it prominently shows the module first of all. When there is not enough space for the module and the type it shows only the module.
> 
> TypeScript: The module is used in the code to filter the suggestions so they all belong to the same module. In this case it is safe to only show the type.
> 
> Go: This is completion on an object rather than generally so no modules are included.
> 
> It is vital that there is a way for the programmer to be able to tell what module each item comes from. Today we show both the module and the type, with the type being in the further details section, which you have collapsed in VSCode so it does not show.
> 
> We could adopt the Rust approach where it shows the type information inline in the instance there is enough space after the module, or we could take some other approach so long as the module is always clear.

I still think showing types inline is good for engineers. Here's an example that shows both type information and module name. What do you think?

Example implementation: https://github.com/gleam-lang/gleam/pull/3364

![image](https://github.com/gleam-lang/gleam/assets/830536/06ce6719-9780-419b-884c-1eb8bc6f5844)

**Comment by lpil** [comment]
Sorry, I must have been unclear in my previous message. How does that present the information when there is insufficient space for both, when you are using the extended completion UI in VSCode, and in other editors? Thank you

**Comment by Zhomart** [comment]
VSCode:

When window is too small, this is what we get:
![image](https://github.com/user-attachments/assets/79b733d8-64c2-4413-99d2-7324519dd316)

This is 50% of 14" screen:

<img width="818" alt="image" src="https://github.com/user-attachments/assets/a3d338b4-98fb-4cef-aaaf-0bdf6f22be59">


This issue was open for some time, and it looks like it didn't get any support (except me :) ). I'll close it, as it looks like people prefer the current approach.
