### ISSUE TITLE
Unified custom type definition syntax

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#355]
Now that structs have been made record compatible (have an atom tag) and now that enums have optionally labelled fields they are equivalent to each other. As this is the case why do we need both?

Introduce a unified way of declaring custom types that can have one or more constructors.

```rust
type Person {
  Person(name: String)
}
```
```rust
type Size {
  Small
  Medium
  Large
}
```

Once this is done we no longer need a `struct` keyword. We could rename anonymous structs to tuples (again). What should the syntax be?

```rust
// Bit long to type and somewhat noisy
tuple(1, 2, 3)

// Confusing with blocks, not similar to the rest of the language
{1, 2, 3} 

// Not similar to anything else in language, hard for newcomers to google
#(1, 2, 3)
[|1, 2, 3|]
[(1, 2, 3)]
%(1, 2, 3)
```

**Comment by michallepicki** [comment]
For tuples, I would vote for `tuple(1, 2, 3)`. I don't think it's too long and noisy, it's shorter than existing `struct(1, 2, 3)` :)

**Comment by EskiMag** [comment]
Is `<1, 2, 3>` totally off or is it worth considering? I like the idea of having the tuple elements inside some brackets where you can see what's an opening and closing one.

**Comment by lpil** [comment]
I think `<1, 2, 3>` would also be possible in the parser.

**Comment by OvermindDL1** [comment]
Could just go the OCaml method for tuples.  Basically the `,` operator.  So `1,2` makes a 2-tuple of 1 and 2; `1,2,3` makes a 3 tuple of 1, 2, and 3; ``1, 6.28, "hi", `Blah`` is a 4 tuple of 1, 6.28, "hi", and the anonymous variant \`Blah.

Traditionally a tuple is written as `(1, 2)` in OCaml, but that's technically unnecessary.  It makes matching very nice though among returns and more:
```ocaml
match something, another_thing with
| 1, 2 -> ...
| ...
```

**Comment by AdamBrodzinski** [comment]
My vote is for `%(1, 2, 3)`. In the Elixir community they were able to pick up on `%{}` very quickly. My second vote would be for `tuple(...)`

**Comment by rjdellecese** [comment]
Should tuples be used often enough (in situations where a proper type—enum or struct—wouldn't be better) that `tuple(1, 2, 3)` is that cumbersome? It would have the advantage of being easier to look up, but how much should that factor in? Would most people be checking a reference, like https://gleam.run/,  when they're learning or looking up language syntax? I genuinely don't know, but that's usually the kind fo thing that I do. Regarding clarity, another disadvantage is that it looks more like standard function invocation than a language operator.

I really like `<1, 2, 3>`, for the same reason that EskiMag mentioned, but I think it does potentially clash a bit with `<<binary>>`. Since angle brackets are so wide, though, at a glance they seem easy to tell apart, so maybe they are well-enough visually distinguishable that it wouldn't be much of an issue.

I don't like `%()` or `#()` as much, but they have the advantage of being a kind of pattern that Elixir and Erlang developers will be familiar with. On the other hand, they have the disadvantage of being two _different_ things, neither of which are tuples, in each of those languages, which might confuse newcomers coming from either.
