### ISSUE TITLE
Can't use os:cmd

### ISSUE THREAD

**Issue by R0DR160HM** [gleam-lang/gleam#3693]
Hi, I'm having a problem running external functions (os:cmd, specifically). I know it is probably my fault, but I've failed to troubleshoot it.

I'm using:
Windows 11 Home
Gleam 1.5.1
Erlang/OTP 27

I have the following code
```gleam
@external(erlang, "os", "cmd")
fn os_cmd(command: String) -> String

pub fn main() {
  os_cmd("echo Hello") // tried other commands too
}
```

And it returns the following error:
```
runtime error: Erlang error

An error occurred outside of Gleam.

erlang:error(Badarg)

stacktrace:
  os.cmd os.erl:721
```

**Comment by giacomocavalieri** [comment]
Hello! The error coming from the erlang function is `badarg`, that means you're calling `os.cmd` with an invalid argument.
Looking at `os.cmd`, it expects the input command to be an erlang string (that is a list of characters); but you're passing it a _Gleam String_ (that is a binary) and so it throws that exception.

Usually when you need this kind of converting between Gleam and Erlang strings you'll need to write a thin wrapper around the external function instead of calling it directly:
```erl
-module(my_package_ffi).
-export([cmd/1]).

cmd(String) ->
  os:cmd(binary_to_list(String))
%        ^^^^^^^^^^^^^^ this is what you need!
```
And then you can call it as an external:
```gleam
@external(erlang, "my_package_ffi", "cmd")
pub fn cmd(string: String) -> Nil
```

**Comment by R0DR160HM** [comment]
"it expects the input command to be an erlang string (that is a list of characters); but you're passing it a Gleam String (that is a binary)"

Oh, didn't know about the difference, my bad
