### ISSUE TITLE
Language server reports wrong type for variables

### ISSUE THREAD

**Issue by giacomocavalieri** [gleam-lang/gleam#3749]
I ran into a strange behaviour on main. If I write the following code:
```gleam
pub type Wibble =
  List(Int)

pub fn main() {
  []
}
```
The inferred type for `main` (and what I get if I let the LS add the type annotation) is `fn() -> Wibble(a)` which is wrong since `Wibble` is not generic and I wouldn't really want it to use the alias even if it were.

It also happens with aliases imported from other modules:
```gleam
// type DecodeErrors = List(DecodeError)
import gleam/dynamic.{type DecodeErrors}

// Inferred as `fn() -> DecodeErrors(a)`
pub fn main() {
  []
}
```

---

edit: another really strange thing is if I add the type explicitly it still adds the type variable. For example:

```gleam
pub type Wibble =
  List(Int)

// Inferred as `fn(Wibble(Int)) -> Nil`
fn wibble(a: Wibble) {
  Nil
}
```

**Comment by lpil** [comment]
Oh dear!! That's not good! 

It may be somewhat fiddly to have it show the correct parameters. The order could have changed in any way, and some could be omitted.

@GearsDatapacks did you have thoughts on this? I know you worked on this also lately.

**Comment by GearsDatapacks** [comment]
I thought I fixed this case, but I think the fix might have been lost when refactoring that code. I'll have a look when I can

**Comment by lpil** [comment]
Ah, hero!!

**Comment by GearsDatapacks** [comment]
So I'm looking into fixing it now, and I've got a partial solution, but I've run into a bit of a roadblock. The first snippet is working great, but the case where the type is imported is slightly trickier. The main tricky part is that we currently have to way to distinguish type aliases from regular types. We need a way so that the second example Jak showed is fixed, but this code still works:
```gleam
import gleam/option.{type Option as Maybe}

const a = option.Some(20)
//    ^ Hovering here should show `Maybe(Int)`
```

**Comment by lpil** [comment]
Why would we need to distinguish them in the type system? That would be a very large item of work that would require quite a lot of design work beforehand.

I've not looked into this so this may be a bad idea, but my initial thought was to have a mapping from the definition parameter indices and the local alias indices. Then you could look at that to determine which (if any) to render, and in what order.

**Comment by GearsDatapacks** [comment]
The printing isn't really the problem here. It's more the matching of types to their names. I could try to implement that, but it would be quite a big rework of the `Names` logic. I understand that distinguishing type aliases from regular types is a big change; it's more in the specific case of when a type is imported, if we could know whether that imported type is a `pub type X { ... }` versus `pub type Y = ...`, that would help fix this. Although in the long term, mapping type variables is certainly desirable, so I'll give it a go.

**Comment by lpil** [comment]
What do you mean by matching of their type names?

>  if we could know whether that imported type is a pub type X { ... } versus pub type Y = ...

I don't think we would need to know that using the system I described above? What can you see that I cannot?

**Comment by GearsDatapacks** [comment]
> I don't think we would need to know that using the system I described above? What can you see that I cannot?

Sorry, this would be for the system I was attempting to implement to fix this

> What do you mean by matching of their type names?

Basically deciding which entry in the `Names` class maps to the type we're trying to print

> ah wait my idea won't work. The parameters may be multiple levels deep: type `X(a) = Y(Z(a))`

Yeah I was just going to point this out. Maybe we can still do it, but only if we don't run into this nested case. That will cover things like:
```gleam
type MyResult(a, b) = Result(a, b)
```
Which are probably the most common anyway. The question is, what should we do about:
```gleam
type MyResult(a) = Result(a, MyError)
```
We can probably correctly resolve this in many cases, but it requires a bit more information to be stored about types. Shouldn't be too tricky to get working though

**Comment by lpil** [comment]
I don't have any good ideas for how to approach this unfortunately :(

**Comment by GearsDatapacks** [comment]
I'll try out my idea and see how far I get.
