### ISSUE TITLE
Spec?

### ISSUE THREAD

**Issue by Rudxain** [gleam-lang/gleam#3907]
- Should Gleam have an official reference specification?
- Does it already have one, and I'm unaware of it?

I think it's worth it. To explain the grammar/syntax, and semantics (such as [type-inference](https://github.com/gleam-lang/language-tour/issues/134))

I'm unsure if I should open this issue [here](https://github.com/gleam-lang/website), because the user-facing docs are hosted there

**Comment by lpil** [comment]
Gleam does not have a specification, no. While it would be nice to have one it is a huge amount of work and since we do not yet have even the funding for 1 full time engineer we cannot afford to dedicate several engineers for an elongated period of time for such a project. All Gleam work must be as cost efficient as possible and have maximal impact for the Gleam ecosystem.

If this is a project you would like to undertake then please do! Though it will need to be in an unofficial capacity.

**Comment by Rudxain** [comment]
Understandable! Also, the compiler's source-code can somewhat play the role of a spec, so I agree

**Comment by lpil** [comment]
Hopefully in future we can have one!
