### ISSUE TITLE
Metaprogramming. Source generator

### ISSUE THREAD

**Issue by Pragrammist** [gleam-lang/gleam#4111]
Here's show source generator concpent, how it can work
In general, you have your project with gleam.toml and project for source generation as test project
You can generate new function, new type, add code to module, and generate new modules with code

https://github.com/Pragrammist/gleam_source_generators_concept

**Comment by GearsDatapacks** [comment]
I don't think this would be a particularly good addition to the language for a few reasons:
- What problem does it solve? (Perhaps you have something specific in mind)
- It makes code harder to reason about. Assuming what you are proposing is running the source generator as the first step of compiling, that obscures the compilation process because the code that you write and read in `src` is not the code being compiled. 
- This doesn't really enable anything new. You could do something similar using Gleam today, and simply manually running some code generator. That gives you all the same ability as this, with the added benefit that you can read the generated code in the source, without having to look at the generator to predict what it will look like

Also, this should probably be a discussion as adding something like this would be a massive change and certainly non-trivial

**Comment by lpil** [comment]
Hello! Here's a blog post that goes into detail on how a large feature could be proposed for Gleam. https://lpil.uk/blog/how-to-add-metaprogramming-to-gleam/

Thank you

**Comment by Pragrammist** [comment]
> I don't think this would be a particularly good addition to the language for a few reasons:
> 
> * What problem does it solve? (Perhaps you have something specific in mind).
 Manual json serelization. For example, in asp.net core due to metaprogramming you can just return object and it will be or xml, or json, or html without manual converting and it save a lot of time. Or generate OpenApi data on the fly without needing to write OpenApi.json. Or make auto documentation of your code, code linting dirrectly in language, not in ide and more. It's too powerfool instrumental to not use. I think you never touch metaprogramming or did it a little, so you cant understand how it's powerfull.
> * It makes code harder to reason about. Assuming what you are proposing is running the source generator as the first step of compiling, that obscures the compilation process because the code that you write and read in `src` is not the code being compiled.
Yes, so I suggest add cli for that, and i think it don't need be in compile time, just through cli. And I also suggested add some rollback if code gen didn't work properly
> * This doesn't really enable anything new. You could do something similar using Gleam today, and simply manually running some code generator. That gives you all the same ability as this, with the added benefit that you can read the generated code in the source, without having to look at the generator to predict what it will look like
I suggest add source generator as Standard future in language and of cli. And also source generators get rids of manual code writing that take a lot time.
> 
> Also, this should probably be a discussion as adding something like this would be a massive change and certainly non-trivial
Yes

**Comment by Pragrammist** [comment]
> Hello! Here's a blog post that goes into detail on how a large feature could be proposed for Gleam. https://lpil.uk/blog/how-to-add-metaprogramming-to-gleam/
> 
> Thank you

It's not big change for LANGUAGE. It's just need add new attribute function(like @external()), and change cli, that's it

**Comment by giacomocavalieri** [comment]
This proposal doesn't address any of the points Louis brings up in the article:
- What are some actual concrete pains that are present in real-world Gleam today that cannot be reasonably solved with any of the options we have today in Gleam? How is this proposal solving those problems?
- What information would the compiler need to know? How would it generate the code? It's not as simple as adding a new annotation, the compiler will have to know how to call those functions at compile time
    - And what happens if the parameters in the annotation are not correct?
    - How would the compiler type check that and how would it affect compilation?
