### ISSUE TITLE
CI builds runs twice per release

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#416]
![Annotation 2020-03-08 111933](https://user-images.githubusercontent.com/6134406/76161807-b9b10f00-612e-11ea-88f7-6d61a09813ef.png)

**Comment by NobbZ** [comment]
It runs twice, because you requested it to do.

You specified in the corresponding `yaml` to run on `create` and on `publish` events. I assume, that both events happen simultaniously and therefore cause 2 builds.

You need to take a closer look at the GA docs to decide which of both is actually correct.

**Comment by lpil** [comment]
Yes, certainly an error on my part! :)
