### ISSUE TITLE
Multiple external functions of the same name

### ISSUE THREAD

**Issue by mgwidmann** [gleam-lang/gleam#419]
Trying to replicate the Elixir `Flow` API to be available in gleam but getting the following issue when defining a function which has (in Elixir) default arguments.

The `Flow.from_enumerable/1` and `Flow.from_enumerable/2` functions are defined as follows:

```elixir
def from_enumerable(enumerable, options \\ [])
```

When trying to replicate this:

```gleam
pub external type Flow(a)
pub external fn from_enumerable(a) -> Flow(a) = "Elixir.Flow" "from_enumerable"
pub external fn from_enumerable(a, Keyword(k, v)) -> Flow(a) = "Elixir.Flow" "from_enumerable"
```

__(Note: not sure whats with the â characters everywhere)__
```
error: Duplicate name

    âââ /Users/matwidma/code/gleam/my_fantastic_application/src/flow.gleam:15:1 âââ
    â
 15 â pub external fn from_enumerable(a, Keyword(k, v)) -> Flow(a) = "Elixir.Flow" "from_enumerable"
    â ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Redefined here
    â

A function has already been defined with the name
`from_enumerable` in this module.
```

While this is true, that function has already been defined, in the Erlang VM these are separate functions, denoted by the number of arguments they take.

Therefore, gleam is incorrect in not allowing the second function to be defined and should only disallow the same name to be defined with the same number of arguments.

**Comment by lpil** [comment]
Gleam does not allow multiple functions with the same name so it is not possible to replicate the untyped Elixir API directly.

The mangled output there is due to a bug in rebar3, perhaps try upgrading it? I'm not sure if the fix has been released yet.

**Comment by mgwidmann** [comment]
Breaking compatibility with other parts of the ecosystem is part of the language design? Erlang defines functions by module, name and arity. Gleam defines only by module name and function name, so this seems counter to Gleam's design to me. You can be more strict, but not less than the runtime environment.

I'm not sure I can agree with this and it seems to me that it goes against [Gleam's principle of being a good citizen](https://gleam.run/index.html#be-a-good-citizen).

Typescript for example has become very popular and I don't think would have done so without complete interoperability with the rest of the ecosystem. I think you should consider reopening this issue because if interop with Erlang/Elixir is broken I don't see much of a future here.

**Comment by lpil** [comment]
Gleam is not Erlang, and as such we don't need to have all the same features. There are countless features that are in Elixir but not in Erlang, and Erlang but not in Elixir such as module namespacing, structs, variable rebinding, differing macro systems, parse transforms, pid literals, etc. None of these are a barrier to clean interoperability between the two languages, and this is the same for Gleam.

All functions defined in Gleam can be called from Erlang/Elixir, and all functions defined in Elixir/Erlang can be called from Gleam. There is no barrier here and nothing is broken.

Further, if you look at all the languages on the BEAM the majority of them do not support the definition of multiple functions with the same name, and it has caused no problems with any of them that I am aware of.

> I think you should consider reopening this issue because if interop with Erlang/Elixir is broken I don't see much of a future here.

I'll be happy to reopen this issue and consider redesign of the language if you can provide an example in which interop between Gleam and Erlang is not possible due to this feature. Thank you.

**Comment by mgwidmann** [comment]
> and all functions defined in Elixir/Erlang can be called from Gleam

The Flow API proves that wrong. Both `&Flow.from_enumerable/1` and `&Flow.from_enumerable/2` are not definable within the same module as external functions. This pattern is quite prevalent in both Erlang and Elixir. Erlang's version of default arguments is more verbose in the source code but thats mostly the difference. Defining an external function for `&Flow.from_enumerable/1` means `&Flow.from_enumerable/2` is not definable and is hidden and vice versa. 

>  if you can provide an example in which interop between Gleam and Erlang is not possible due to this feature.

All functions with different arity in erlang are not possible. The largest arity functions hide the smaller arity functions. Granted the ones with the same name and lesser arity usually using defaults which Gleam users would have to always supply, but its not guaranteed. For example, take these two functions (using Elixir because my Erlang is not so great):

```elixir
def my_function(a) do
  Logger.info("This function is hidden and impossible to call when the 2 arity function is defined in Gleam")
  "You passed me #{inspect a}"
end

def my_function(a, b) do
  "You passed me both #{inspect a} and #{inspect b}"
end
```

These are completely independent functions and do not have any relationship in the runtime. Forcing the user to define one or the other means some functions are not reachable without defining a new module in Gleam.

**Comment by lpil** [comment]
> Defining an external function for &Flow.from_enumerable/1 means &Flow.from_enumerable/2 is not definable and is hidden and vice versa.

I think you are mistaken, both these functions can be defined and used in Gleam

```rust
pub external type Enumerable(t);
pub external type Flow(t);

pub type Option {
  // options go here
};

pub external fn from_enumerable(Enumerable(t)) -> Flow(t)
  = "Elixir.Flow" "from_enumerable";

pub external fn from_enumerable_with_options(Enumerable(t), List(Option)) -> Flow(t)
  = "Elixir.Flow" "from_enumerable";
```

If you could explain the task you are trying to perform I could give more specific help.

**Comment by mgwidmann** [comment]
I was trying to create a wrapper library for interacting with Flow in Gleam. Making a new function name means the API won't align with the original anymore. What happens when there is 2, 3, or 4 default arguments. I don't think your solution scales well.

**Comment by gamebox** [comment]
I think the miscommunication here is the thought process of programming in a dynamic language and a static language.  In a dynamic language you want to have an API where you can just throw something at the function call and the caller will figure out what to do.  In a static language like Gleam, you have to be more explicit with how you call functions.  Its more verbose, but also more readable(this is somewhat subjective though)

**Comment by mgwidmann** [comment]
> This hasn't been a problem in any other language without function overloading (including the majority of BEAM languages), why is it a problem for Gleam?

I would argue that it has been a problem. Look at golang which has this same issue: https://github.com/golang/go/issues/21659

You end up with a lot of the same functions but with stupid names. Look at that example in that issue. Often the names come with the type of either the return or the input of one of the parameters in the name because theres no way to differentiate them. 

> I think the miscommunication here is the thought process of programming in a dynamic language and a static language.

I'm not so sure thats the issue here. This is general good API design. You want your function calls to read like sentences, including the parameters and Gleam's labels to those parameters. Having to make a differentiator in the middle muddies it up. Most statically typed languages solve this with function overloading. I'm not arguing for function overloading as I think thats better handled with case statements and type unions personally (though type unions is off topic here).

I don't see a drawback to simply including arity in the method signature. MFAs are a pretty standard thing in the ecosystem. What does Gleam gain from the current approach? Users of any other flavors of Erlang development will be surprised at this. And when the names to external functions are different than an already familiar API (such as Flow) you get divergence in readability because readers have to be reminded what difference is between things like (as in Go) `FindAllStringIndex ` vs `FindAllIndex`.

**Comment by lpil** [comment]
I don't think you've presented any concrete examples of problems beyond a personal dislike of "stupid" names. I personally think this style of naming is better. Much like syntax and other unimportant matters of opinion there is no technically superior approach to naming, andthere's no point continuing to discuss preferences.

I'm considering this discussion done for now, but please do feel free to re-open it if you have a technical reason for this feature.

**Comment by japplegame** [comment]
> Gleam does not allow multiple functions with the same name

To me, it looks like a meaningless restriction.

**Comment by lpil** [comment]
@japplegame How would the type checker support this?

```rust
pub external fn from_enumerable(Enumerable(t)) -> Flow(t)
  = "Elixir.Flow" "from_enumerable";

pub external fn from_enumerable(Enumerable(t), List(Option)) -> Flow(t)
  = "Elixir.Flow" "from_enumerable";

pub fn main() {
  from_enumerable
}
```

What type does `from_enumerable` return?

**Comment by pd-andy** [comment]
> > Gleam does not allow multiple functions with the same name
> 
> To me, it looks like a meaningless restriction.

@japplegame it's worth investigating a little into the difference between _parametric_ and _ad-hoc_ polymorphism. Having multiple function definitions with the same name, or _overloading_, is an example of the latter. Besides subtyping, ad-hoc polymorphism is (or in some cases, _was_ – more on that later) very popular in many maintstream languages (c++, typescript, java, ...) and so it might appear trivial or nonsensical for a language _not_ to have such a feature, but it's not really that simple.

Gleam's type system is actually unlike those languages in quite a lot of ways, it has much more in common with languages like Elm, Haskell, or OCaml; all of which derive from a type system known as [Hindley-Milner](https://en.wikipedia.org/wiki/Hindley–Milner_type_system). Importantly this type system has _parametric_ polymorphism: typically known as "generics" in the languages you might be familiar with. 

Adding ad-hoc polymorphism to HM-derived type systems is not trivial, both in terms of technical difficulty and usability. Haskell has typeclasses, OCaml has module functors, Rust has traits, Elm has a handful of constrained typeclasses but otherwise does not have any ad-hoc polymorphism at al, ... Such features are often considered quite advanced in those languages, but they also end up becoming idiomatic (good luck navigating a Haskell codebase without understanding typeclasses) and so there's a genuine design decision to be made over whether or not to implement them.

HM type inference has a lot of desirable features (described in the link above) and extending with ad-hoc polymorphism tends to complicate and erode some of that. There's also the fact that overloads are often _avoided_ in some communities and programming styles because they can make both your code and the compiler's error messages less clear. 

---

There's a really excellent comment exploring different types of polymorphism here: https://github.com/gleam-lang/gleam/discussions/1244#discussioncomment-1429135 (which incidentally is a comment in a discussion around adding ad-hoc polymorphism to Gleam)

There is also an open discussion about if/how to implement optional arguments in Gleam which is another solution to the specific complaint brought up in this (quite old) issue. 

Always a good idea to read what's been discussed in the past before barging in to let people know their decisions are meaningless!

**Comment by japplegame** [comment]
@pd-andy why do you think I don't know about the types of polymorphism? I know everything you wrote about.

Apparently I didn't express myself exactly.
I'm not talking about polymorphism at all. I'm talking only about arity based function overloading.
I'm sorry if I put it wrong.

**Comment by lpil** [comment]
Overloading could be an option. Could you explain how we would solve the issues described in my post @japplegame ? They apply to overloading rather than ad-hoc polymorphism such as traits.

**Comment by japplegame** [comment]
> Overloading could be an option. Could you explain how we would solve the issues described in my post @japplegame ? They apply to overloading rather than ad-hoc polymorphism such as traits.

Just like in Elixir. Specify the arity explicitly in some way

**Comment by lpil** [comment]
That would work for functions with different arity, but not those with different types. It would also make the syntax much more verbose.

**Comment by japplegame** [comment]
> That would work for functions with different arity, but not those with different types.

I'm talking only about arity based overloading.

 > It would also make the syntax much more verbose.

Could you give an example of additional verbosity?

**Comment by lpil** [comment]
> I'm talking only about arity based overloading.

In which case you can implement this yourself by adding a number to the function name

```rust
pub fn main() {
  let x = myfunction2
}
```

This is less verbose than having a special syntax for it like Elixir and Erlang do.

```rust
pub fn main() {
  let x = fn myfunction/2
}
```

Other good things about doing it this way include

- We could implement optional arguments alongside labelled arguments
- We would not have to downgrade the pipe operator to have the same limitations as the Elixir one
