### ISSUE TITLE
Docker image with Gleam + Erlang

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#515]

**Comment by lpil** [comment]
@CrowdHailer Shall I assign this to you?

**Comment by CrowdHailer** [comment]
Yes I can tackle this

**Comment by CrowdHailer** [comment]
First version of a dockerfile for gleam is here. https://github.com/did-app/midas-template/blob/master/Dockerfile

I looked through the information on becoming an official image. It looks like it's shouldn't be too hard to do if we want to go through all the steps. 
https://github.com/docker-library/official-images

@lpil I have a problem running this image in Docker compose. It's good to not map generated files back to the host machine. And I do that by specifying volumes in the compose file. 

https://github.com/did-app/midas-template/blob/master/docker-compose.yml#L14

Currently this doesn't work because the gleam compiler tries deleting the gen directory.

Is it possible to
a) specify a directory for generated files other than gen in the project.
b) update the compiler code so it deletes the contents of gen but not gen it's self. 

I assume rebar3 only ever deletes the contents of _build because I do not have the same problem with that directory.
My preference would be for option b, so change gleam to only try and delete the contents of the gen directory

**Comment by CrowdHailer** [comment]
Pushed a latest tag to the gleam repository on docker hub.

When 0.8.0 is released I can create a tagged version on docker hub too.

**Comment by lpil** [comment]
What's the problem with deleting the gen directory? It looks like you could delete the gen and _build lines from your compose file and it would work ok?

I've not used docker compose in a few years so perhaps I'm missing something.

**Comment by CrowdHailer** [comment]
I mount a gen and _build directory inside the container so that generated files don't end up on the host machine. They are mounted after the source directory so overlay the _build and gen from the host machine and generated files stay in the container.

You don't want generated files on the host machine.
- They should never be committed into source control, but that's covered by .gitignore so no big deal.
- Some docker implementations do a lot of work copying files from the docker filesystem and host file system, so if you have gleam watch have to always write the generated files could slow things down.
- The generated files when copied to the host machine are owned by docker so you need to use `sudo` to delete them.

So yes, today I have deleted the gen line and it works for me. But I'm on Linux, so point 2 doesn't effect me much and I know how to handle point 3.

**Comment by lpil** [comment]
Thank you for the extra info.

**Comment by CrowdHailer** [comment]
I'm just pushing up the 0.8.0 images now. 
Would you be agreeable to adding something to the gleam-lang/gleam repo that built them automatically.

There is this option for a github action https://github.com/marketplace/actions/publish-docker#tag_semver

Also it can be done by setting up build rules on dockerhub

**Comment by lpil** [comment]
Automatic building sounds good. Would we want to use GitHubs image registry seeing as we use them for everything else?

**Comment by CrowdHailer** [comment]
It's free to host on docker hub, also if you get official image status on docker hub then it's a smaller amount of typing. 

Actually thinking about it I think it's shorted to use docker hub, official or not
