### ISSUE TITLE
Hot Code Reloading / relup / appup

### ISSUE THREAD

**Issue by paulreimer** [gleam-lang/gleam#557]
Very excited to start using Gleam, I'm wondering about the hot code reloading / releases / relup parts of OTP, can we use these -- or similar -- with Gleam?

**Comment by lpil** [comment]
Hi there! Thanks for checking out Gleam.

All the usual Erlang code reloading features work, but it is not possible to type check the upgrades themselves as we have no way knowing the typed of the already running code. This means you would have the usual Erlang amount of safety rather than what you might have with Gleam otherwise.

Generally the OTP libraries for Gleam are optimised for type safety rather than upgrades, and use records rather than atom modules so the state upgrade callbacks may be slightly more complex to write.

I see hot code upgrades as not being a primary goal of Gleam at present.

**Comment by paulreimer** [comment]
Thank you! That's good information to know.
