### ISSUE TITLE
Should we introduce an option type?

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#591]
Option is a type used for representing values that may not be present. It is defined like so:

```rust
pub type Option(a) {
  Some(a)
  None
}
```

The implementation and behaviour is near identical to Result:

```rust
pub type Result(a, e) {
  Ok(a)
  Error(e)
}
```

Typically all functions implemented on Option will be dupliations of those on Result, and function will be needed to convert between the two.

In Gleam so far we have been using `Result(a, Nil)` as an alternative to `Option(a)`, which remove this duplication and any need to casting between the two types.

Should we add an Option type to Gleam?

## Considerations

There is no precedence for an Option type on the BEAM, while Result is widely used.

`None` may read better than `none()` or `Error(Nil)` for users who are familiar with Option in other languages that have Option.

Currently Gleam has only a single error flow control type, this would mean introducing a second. How would `try` work with this second flow control type?

**Comment by jkomyno** [comment]
To me, the difference between `Option` and `Result` is the same as the difference between `Maybe` and `Either` in Haskell. In Haskell, it makes sense to keep them separate because they convey different semantics. Sometimes, having an empty result doesn't mean that an error occurred.

**Comment by Qqwy** [comment]
On top of what @jkomyno already said: There are more functions you can write for `Option(a)` than for `Either(a, b)` because you have a well-defined 'default value' at all times.

**Comment by lpil** [comment]
> To give you an example: Haskell's Data.Maybe.listToMaybe returns the first element of a list, or Nothing if the list is empty. It is not possible to write this function (as a total function) for Either/Result.

This isn't accurate, we happily have this kind of function implemented using Result in Gleam, and so does both Elixir and Erlang.

**Comment by alexeypetrushin** [comment]
I prefer how it's done in TypeScript, as specific case of literal type

```
type Optional<V> = V | undefined

function return_number_maybe(): Optional<number> {
  return Math.random() > 0.5 ? 1 : undefined
}

const result = return_number_maybe()

console.log(result + 1) // Error can't add 1 to Optional

if (result != undefined) {
  // Now working, result autocasted to its V type - number
  console.log(result + 1)
}
```

**Comment by lpil** [comment]
@alexeypetrushin Gleam's type system is very different to Typescript's, that system is not possible.

**Comment by QuinnWilton** [comment]
> How would try work with this second flow control type?

At least in the ways that I've always used and seen them used, option types aren't a flow control type in the same way that result types are. They're used to denote that a value is optional (as in the case of configuration), or that a given function is not total over its domain (like the `listToMaybe` example).

`Result(a, Nil)` is functionally equivalent to `Option(a)`, but I think there's a slight semantic difference between how the two are often used: with `Result`, the other type is usually meant to be the type used by failures. With `Option(a)` though, the `None` constructor doesn't imply failure, it just implies a lack of value.

In light of that, I'd argue that `try` shouldn't be used for option types. With a `Result`, if the computation fails, you want to return early. But with an `Option`, if you see a `None`, rather than returning early, it's more likely that you just won't do some additional computation. I suppose both of those perspectives really map to the same underlying concept, but I do think that they're two semantically different ways of viewing the same problem, and that at the very least, there's a readability win to be made by differentiating between both intents.

All of that being said, I don't particularly have an issue with using `Result(a, Nil)` myself, but I think it is a language feature that will cause some rub with many programmers coming from other statically typed functional languages.

**Comment by lpil** [comment]
Great feedback and reasoning everyone. I'll leave this open for a little while longer for other people to chime in if they want to, then we'll make a decision.

**Comment by lpil** [comment]
Alright! Thanks everyone! Let's add Option :)

**Comment by CrowdHailer** [comment]
Is it possible to have Some/None be aliases to constructors Ok(v) and Error(Nil) under the hood.

Then `try` would work, try would also work in the case where some steps were using Options and others, perhaps because wrapping an elang library are using Error(Nil)

**Comment by lpil** [comment]
One of Gleam's design rules is that there should only be one way to express something, especially for syntax. Because of this I don't want to introduce duplicate constructors for the same records.

Also I think this would be confusing when the pattern None matches the value Error(Nil).

**Comment by CrowdHailer** [comment]
Fair points.

My biggest reason for wanting Option is for the cases when I want to return `Result(Option(value))` 
e.g. get user from db. Error for connection failure None when no user. 
Same for getting a session Error for Invalid Headers, possibly attackers/bots. None for new user without Session.

My biggest reason for liking not having an Option type is never having to choose. I think occasionally there are cases where Error(Nil) is the right semantics. Can't think of an example right now though.

**Comment by lpil** [comment]
That was the original reasoning, but the feedback has been overwhelmingly that two types are wanted.

In practice I've found the use the same as one had to make the same decision about whether to use Result(a, Nil) as they do about whether to use Option now.

The deciding factor between Option and Error in cases where it is not obvious for me has been whether it could be considered an error case and thus whether I would want to use try. This has steared me towards always using Error(Nil) as the return value for a lookup that returns nothing, and using Option for optional fields and optional arguments. Thinking about how we describe these things I this makes sense- we rarely say "an optional return value".
