### ISSUE TITLE
List module constants in generated HTML docs

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#665]

**Comment by thehabbos007** [comment]
Do we want to provide the type of the constant in the documentation text, or should we expect it to be obvious from the formatted code?

![image](https://user-images.githubusercontent.com/6988668/85321458-f843bd00-b4c4-11ea-8810-6a31f98f6a5d.png)

**Comment by lpil** [comment]
That looks great!

It would be nice to also render the type annotation like so:

```
pub const test: String = "2"
```

**Comment by thehabbos007** [comment]
I ran into some issues in regards to ensuring type annotations in the formatted documentation output.

Since the code might not have annotations, it would need to be extracted from the TypedStatement with its inferred type, but I am unsure how to translate the inferred Arc<Type> into the proper string representation, is there a function to do so already?

**Comment by lpil** [comment]
Ah yes! You can use the type printer: 

https://github.com/gleam-lang/gleam/blob/main/src/format.rs#L863

https://github.com/gleam-lang/gleam/blob/main/src/format.rs#L882
