### ISSUE TITLE
Discard in bit string pattern renders invalid Erlang

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#704]
```rust
case x {
 <<_:utf8, rest:binary>> -> True
  _ -> False
} 
```

The `_` doesn't get rendered in the Erlang.

```rust
case x of
 <</utf8, Rest/binary>> -> true;
  _ -> false
end
```

**Comment by namoscagnm** [comment]
Hi, I would like to try this one. Could you assign it to me, please?
Thanks!

**Comment by lpil** [comment]
Sure thing

**Comment by namoscagnm** [comment]
Hi, the same code doesnt even compile. After typing gleam build, I get:
![image](https://user-images.githubusercontent.com/15790478/86143039-360f9980-baf4-11ea-926a-febcd73d1a3d.png)


I tested it with the following code:
![image](https://user-images.githubusercontent.com/15790478/86142824-f183fe00-baf3-11ea-871f-e38d7b9848bf.png)

Actually, gleam format will not even let me format it because of the same warning

**Comment by lpil** [comment]
What version of Gleam are you using? You'll need v0.10.0-rc1 or higher as that is when the bit string syntax was released. 

For this work I'd recommend using the main branch. The compiler can be run from source with `cargo run build path/to/gleam/project`

**Comment by namoscagnm** [comment]
Oh!  I was using the version I got from pacman, which is 0.9.something. Now I can see the output as you described, thanks :)

**Comment by namoscagnm** [comment]
Hi, as I am new to the project I would like to ask following questions to avoid investigating into parts of the code that are not relevant and help me debugging it:

1) Do you have a feeling whether the problem lies on the parsing of the AST (The ast doesnt recognize it), or do you think the AST understood it correctly, but translating it is faulty?

2) In which commits creates the AST, and which prints it?

3) Is there a way of printing the AST?

Of course, if you have a hint of which files to look on, that would also be helpful :)
Thanks!

**Comment by lpil** [comment]
For sure, I'm on my phone so I may be a little brief.

I suspect the problem is not in the passing but instead in the rendering of the erlang in the erl module. I would look for the function that turns a bit string pattern into a Document and see what it does for discard variables.

I'm not sure what you mean about commits I'm afraid.

You can prints rust data types using the dbg! macro.

I would probably start this by creating a failing test in the erl tests that replicates the problem.

**Comment by namoscagnm** [comment]
Interesting. If I make the input be

```
case x {
 <<_age:utf8, rest:binary>> -> True
  _ -> False
} 
```


The output is **almost** correct and reads:

```
case x of
 <<_age/utf8, Rest/binary>> -> true;
  _ -> false
end
```
Note the non-capitall letter a (of age). Normally it should be a block letter.

I have the feeling this is being read as a string. This would explain why it fails the benchmark of the issue, but doesnt fail the case I presented just now.

I have also the feeling this should be due to a missing pattern around on line 293 of erl.rs:
https://github.com/gleam-lang/gleam/blob/8fb1d31c11f93e537741cc80bec58227e5143c72/src/erl.rs#L300

Which is being called by a bitstring on:

https://github.com/gleam-lang/gleam/blob/8fb1d31c11f93e537741cc80bec58227e5143c72/src/erl.rs#L717

1) Do you think I am on the right path?
2) What is the desired output for the second case I showed: _Age, _age,  or _age? I would suggest _Age

ps: I dont have a debugger setup yet, so it might get easier when I get one

**Comment by lpil** [comment]
I'm a little confused as I don't have the same behaviour as you for that example. Both `_` and `_age` render `<</utf8` for me, which is invalid. Which version are you using?

I think the problem is here: https://github.com/gleam-lang/gleam/blob/main/src/erl.rs#L374

It is rendering nothing for `Discard` patterns when it should render the variable name.

> What is the desired output for the second case I showed: _Age, _age, or _age? I would suggest _Age

They're both valid Erlang, so keeping it the same with `_age` may be the more straightforward way to do it.

**Comment by lpil** [comment]
Actually it may be good to replace that `Document::Nil` with a call to the `fatal_compiler_bug` function so that we don't silently fail in future.

**Comment by namoscagnm** [comment]
> Which version are you using?

Im using 0.10.0-rc2
