### ISSUE TITLE
Can't build freshly created project

### ISSUE THREAD

**Issue by MainShayne233** [gleam-lang/gleam#719]
```sh
❯ gleam --version
gleam 0.11.0-dev
```

Expected behavior: I should be able to create a new gleam, `cd` into it, and run `gleam build` to  build the project.

Actual behavior:

```sh
~/gleam
❯ gleam new my_lib
* creating my_lib/LICENSE
* creating my_lib/.gitignore
* creating my_lib/README.md
* creating my_lib/gleam.toml
* creating my_lib/test/my_lib_test.gleam
* creating my_lib/src/my_lib.gleam
* creating my_lib/.github/workflows/test.yml
* creating my_lib/rebar.config
* creating my_lib/src/my_lib.app.src

Your Gleam project "my_lib" has been successfully created.
The rebar3 program can be used to compile and test it.

    cd my_lib
    rebar3 eunit


~/gleam
❯ cd my_lib/

~/gleam/my_lib
❯ gleam build

error: Unknown import
  ┌─ /home/shayne/gleam/my_lib/test/my_lib_test.gleam:2:8
  │
2 │ import gleam/should
  │        ^^^^^^^^^^^^ did you mean `my_lib`?

The module `my_lib_test` is trying to import the module `gleam/should`,
but it cannot be found.
```

However, if I run any `rebar3` step that trigger a compilation, then `gleam build` succeeds!

**Comment by lpil** [comment]
Gleam build is not yet intended to be used directly as it only knows how to compile Gleam into Erlang, so you'll need to run rebar3 instead in order to compile a full project.

We give these instructions in the output when creating a new project, but it's still really confusing!

Currently we're working on having the compiler also be the build tool so the user doesn't have to switch from one CLI program to another to build their project. Things should be friendlier then hopefully.

**Comment by MainShayne233** [comment]
Awesome! That makes sense. Thanks for the detailed explanation. :slightly_smiling_face:
