### ISSUE TITLE
Parameterised types are leaking between type definitions in a module

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#734]
This should be a type error as `a` is not in scope for `B`

```rust
type A(a) {
  A
};

type B =
  a
```

**Comment by QuinnWilton** [comment]
I briefly looked into this tonight, and while I found the issue, I don't see a quick fix. Did you have something in mind?

As far as I could tell, the problem is that `register_types` calls `make_annotated_type_vars` for all of the statements in the module, which adds those type vars into the top level scope. It's also not enough to just make a new scope for each statement, because we need to be able to make use of those type vars when later constructing types.

I feel like what we want is the ability to associate type vars with a type constructor, so that we can later override the current scope's type vars (or possibly merge them?) with the type constructor's type vars as needed. This seemed like a larger refactor than would warrant the "good first issue" label though, so I wasn't sure if I was missing something obvious.

**Comment by lpil** [comment]
I think type vars should be preserved within a statement but be reset between statements. I don't think preserving them between statements does anything because we will instantiate the generic vars into unbound ones when we reference another statement within a function.
