### ISSUE TITLE
Warn if all fields are given in a record update

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#740]
```rust
pub type Person {
  Person(name: String, age: Int)
}

pub fn main(person) {
  Person(..person, name: "Tim", age: "44")
}
```

**Comment by QuinnWilton** [comment]
Sorry to revisit this issue after it's been closed, but I'm wondering whether this behaviour is the right approach.

I just had a situation where I had a datatype with one field, and so to avoid this warning, I needed to update it by creating a new record each time, rather than by using the spread syntax. This was fine, but when I later added new fields to the type it meant that those previous constructor calls were incorrect, and needed to be changed to account for the new fields.

In light of that, I'd argue that for records with one field, there's a semantic difference between:

```
MyType(..old, field: old.field + 1)
```

and:

```
MyType(field: old.field + 1)
```

In the first situation, I'm explicitly saying that I don't care about any other fields that might exist, whereas in the second I'm saying that I want explicitly set every field on the record.

This definitely isn't a big deal at all, but it feels like a surprising gotcha.

**Comment by lpil** [comment]
Would we have a special case for a single field, or would you expect this to hold true for when there's multiple?

**Comment by QuinnWilton** [comment]
That's an interesting question! I was thinking that it would always hold true, because that sort of special casing tends to make me uncomfortable, and I think a programmer would find it surprising.

I also understand the value of this warning though, so I'm not sure what the right call is.
