### ISSUE TITLE
Permit changing of parameterised types with record updates

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#745]
```rust
pub type Box(a) {
  Box(tag: String, value: a)
}

pub fn insert(box: Box(a), value: b) -> Box(b) {
  Box(..box, value: value)
}
```

We must ensure that if the parameterised type is used for multiple fields that those fields are all updated with the same type.

Follows up from https://github.com/gleam-lang/gleam/issues/588

**Comment by e-hat** [comment]
Not exactly volunteering for this yet, but I was taking a quick look.

Would it be possible to implement the spread feature instead as a kind of syntactic sugar? Like instead it just creates a `Call` node with arguments patched together from the spreaded object and the explicit arguments? 

Something like `Box(..box, value: value)` -> `Box(tag: box.tag, value: value)`. Where does a transformation like this usually occur in the codebase? In this case, it would probably have to happen during type inference since we still need to infer the types of the object being spreaded and the constructor itself.

P.S. this approach would be staying true to this bit from the language tour 🙂 
```
As Gleam records are immutable the update syntax does not alter the fields in place, 
instead it created a new record with the values of the initial record with the new values added.
```

**Comment by lpil** [comment]
It's possible but we would want to retain all the information that it is a spread so that the information can be used by LSP refactorings and compiler optimisations in future. Going forward any feature that is effectively syntactic sugar that gets erased is going to be converted over to some form that preserves all the information.

**Comment by lpil** [comment]
Having said that, it's possibly more valuable to process it as a call in the immediate term in order to get this extra functionality.
