### ISSUE TITLE
Parentheses and order of operations is respected while evaluating mathematical expressions

### ISSUE THREAD

**Issue by cschembor3** [gleam-lang/gleam#778]
I'm not sure if this is a part of the plan for the language, but it would be nice if we respected parentheses while evaluating expressions.

Currently, doing something like this:
```
let x = 2 * (2 - 1)
```

does not actually compile. Trying to open the interactive Erlang shell gives the following error message:
```
error: Syntax error
    let a = 2 * (2 - 1)
                ^ Unexpected token

Expected one of "<<", "[", "[]", "case", "fn(", "todo", "todo(", "tuple", "{", r#"\"(([^\\\\\"]|\\\\.)*)\""#, r#"-?[0-9]+\\.[0-9]*"#, r#"-[0-9]+"#, r#"[0-9]+"#, r#"[A-Z][0-9A-Za-z]*"#, r#"[a-z][0-9a-z_]*"#

===> Unable to compile Gleam project
```

I think it would be nice if `a` gets evaluated to 2.

Are there currently any plans for something like this?

**Comment by lpil** [comment]
Hello!

Blocks in Gleam are written using {} rather than (), so `2 * {2 - 1} ` will do the trick.

The reason for using {} is to remove ambiguity in the parser between blocks and function calls. If we use () for blocks we will likely need to introduce semicolons between lines, which is something I would like to avoid.

**Comment by cschembor3** [comment]
Ahh, my mistake! Thanks for clearing this up!

**Comment by lpil** [comment]
No mistake! This isn't very clear from the docs.

**Comment by cschembor3** [comment]
No problem. Thanks again @lpil. I'll go ahead and close this issue.
