### ISSUE TITLE
Incorrect error format when given an unexpected record update field

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#785]
![image](https://user-images.githubusercontent.com/6134406/92713917-6de85800-f353-11ea-93d0-d2995ac07722.png)

**Comment by lrosa007** [comment]
I can do this over this weekend

**Comment by lpil** [comment]
Thank you.

I'm afraid I was in a rush when I found this so I was unable to create a minimal reproduction. Do you think you'll need more info to get started?

**Comment by lrosa007** [comment]
I'll comment here again if I have a hardtime with anything, should be ok to get started

**Comment by lrosa007** [comment]
this is what I'm getting when I try to replicate your screenshot.

<img width="651" alt="Screen Shot 2020-09-11 at 5 26 43 PM" src="https://user-images.githubusercontent.com/12070598/92974379-0bc34c00-f454-11ea-9143-d2e0169353ad.png">

Is the bad formatting around that "did you mean?" not exactly sure what the problem is.

This is using latest main

**Comment by lrosa007** [comment]
this is what I'm getting when I try to replicate your screenshot.

<img width="648" alt="Screen Shot 2020-09-11 at 5 31 05 PM" src="https://user-images.githubusercontent.com/12070598/92974595-986e0a00-f454-11ea-9615-3e4b9ef346e4.png">

Is the bad formatting around that "did you mean?" not exactly sure what the problem is.

This is using latest main

**Comment by lpil** [comment]
Very strange. I'll try and reproduce this myself shortly.

**Comment by lpil** [comment]
I've been unable to replicate this, sorry @lrosa007 . Thanks for your help, I'll make a new issue if I stumble upon this problem again
