### ISSUE TITLE
Discarded variables don't increment in ouputed erlang

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/gleam#788]
```rust
let _r = 1
let _r = 2
```

This code runs with this failure.

`** (MatchError) no match of right hand side value: 1`

I think  it's making erlang code that looks like the following.
```erl
_R = 1
_R = 2
```

**Comment by lpil** [comment]
Oops, thank you!

**Comment by mrgleam** [comment]
@lpil I try to fix this issue. I found Erlang code looks like in picture
<img width="147" alt="Screen Shot 2563-09-25 at 17 12 57" src="https://user-images.githubusercontent.com/11692854/94255602-afcbed80-ff52-11ea-8aae-61227200275c.png">
<img width="234" alt="Screen Shot 2563-09-25 at 17 13 03" src="https://user-images.githubusercontent.com/11692854/94255612-b22e4780-ff52-11ea-954b-f201af5ace16.png">

and I debug in local_var_name function. I never seen _r pass to this function
<img width="642" alt="Screen Shot 2563-09-25 at 17 13 20" src="https://user-images.githubusercontent.com/11692854/94255688-d558f700-ff52-11ea-9604-d411c2b792e2.png">

Can you have suggest me?

**Comment by lpil** [comment]
Hello, thank you for helping out with this.

That code does not currently get called for discard patterns, which is why this bug is occurring.

To me it seems there are two options. We could either update the code to use the code you linked when rendering discount patterns, or we could make it so discard patterns always render _, discarding the name. I would be happy with either, and the latter would be easier to implement.

Does that help?

**Comment by mrgleam** [comment]
Thank you very much. Let me try.

**Comment by mrgleam** [comment]
@lpil for "or we could make it so discard patterns always render _, discarding the name."

Do you mean replace this line

<img width="595" alt="Screen Shot 2563-09-30 at 18 10 32" src="https://user-images.githubusercontent.com/11692854/94678273-6875a080-0348-11eb-8b8d-f39e9f3385ca.png">

to

<img width="518" alt="Screen Shot 2563-09-30 at 18 10 19" src="https://user-images.githubusercontent.com/11692854/94678300-74616280-0348-11eb-8892-eed899d6c58a.png">

right?

**Comment by lpil** [comment]
Yes that would do it!
