### ISSUE TITLE
Type inferred too weakly: usage not taken into consideration

### ISSUE THREAD

**Issue by Janiczek** [gleam-lang/gleam#790]
I'm unsure how is the type inference of Gleam implemented (is it Hindley-Milner or not?) but it seems to me that the usages of functions are not taken into consideration when inferring their type.
This code:
```gleam
fn count_down() { -- String
  "3... 2... 1..."
}

fn blast_off() { -- `a` if looked at locally, String if looking at usages
  todo
}

pub fn launch() { -- List String
  [
    count_down(),
    blast_off(),
  ]
}
```
emits this warning:
```
warning: Todo found
   ┌─ /home/martin/Localhost/otp/test_gleam/src/test_gleam.gleam:20:3
   │
20 │   todo
   │   ^^^^

I think this should be an `a`.

This code will crash if it is run. Be sure to remove this todo before running
your program.
```
where the inferred type is `a` where I thought I'd get a `String`.

Reasons for String:
* we can't get much information about the type from actual body of `blast_off()` - so it's an `a`
* in the `launch()` function body, it's in the same list as `count_down()` which is a `String`
* lists in Gleam are homogenous, so if any of its elements is `String`, it must be a `List String`
* thus, `blast_off()` must be a `String` by the virtue of being an element of a `List String`

**Comment by lpil** [comment]
This isn't a mistake, but I can see how it is unexpected.

The function `blast_off` has the type `a` because it never returns, and as such can be used anywhere. In Rust this would be called `!`, but we don't have a dedicated no-return type so a type variable will do.

Here's the same code in Haskell, if you try it you'll see that it type checks successfully

```haskell
countDown =
  "1, 2, 3"

blastOff =
  error "todo"

launch =
  [ countDown
  , blastOff
  ]
```

And here's the types being introspected in the GHC REPL

```
:t countDown
countDown :: [Char]
:t blastOff
blastOff :: a
:t launch
launch :: [[Char]]
```
The implemention you've given with `todo` is the only valid implemention of a function of `fn() -> a` in Gleam, so if it was changed in any fashion the type would also have to change, and any resulting type errors would be caught by the type checker.

More generally any function that has been inferred and does not call any functions that have not yet been inferred can be safely generalised to the more general type. No later uses (such as the one in `launch`) can influence the typing of the function.

> I'm unsure how is the type inference of Gleam implemented (is it Hindley-Milner or not?)

Yes, Gleam is HM, specifically Algorithm W.

**Comment by Janiczek** [comment]
Ah, thanks for the explanation! That makes a bit more sense to me now :)

So `todo` is always of an unbound type (`a` in this case), never some other concrete type?

----

Sidenote - where I'm coming from: I believe in Elm this works differently, IMHO the `a` inferred by `Debug.todo "foo"` is later unified with all the other type information (including the annotations and usages).

I don't have a proof for this as Elm 0.19.x doesn't show warnings for missing type annotations anymore, and I couldn't get an 0.18.0 version to work (missing binaries or something? :shrug: ).

So it's mostly a gut feeling, rather than a hard evidence. But I believe a code snippet like this:
```elm
bar =
    Debug.todo "bar"

list : List String
list =
    [ "foo"
    , bar
    ]
```
would generate a warning for `bar` suggesting it should be a `String`, not an `a`.

**Comment by Janiczek** [comment]
Closing this myself as it's an intended behaviour.

**Comment by lpil** [comment]
I _think_ Elm behaves the same way as Haskell and Gleam. I tested with this code in the REPL and it type checked

```elm
let
   todo = Debug.todo ""
   ints = [1, todo]
   strings = ["", todo]
in 1
```

I wasn't able to work out how to make Elm print the types though. Perhaps if we rendered the docs?

**Comment by Janiczek** [comment]
That code snippet is illuminating. I guess you're right then! At least I can't think of an example that would prove you wrong.

This whole thing makes me think of let polymorphism for some reason :sweat_smile: But I guess this only superficially related:
```elm
foo : a -> String
foo _ = "foo"

let
  x = foo ()
  y = foo 1
  z = foo "bla"
in
1
```

> I wasn't able to work out how to make Elm print the types though. Perhaps if we rendered the docs?
I think your best bet would be to hack some logging of inferred types into the Elm compiler. Hint: for the lack of `derive Show` calls it's not a nice ride :)
