### ISSUE TITLE
Unknown types in case

### ISSUE THREAD

**Issue by sporto** [gleam-lang/gleam#802]
By mistake I wrote something like this.

```
fn(value: bool) {
	case value {
		true ->
			...
		false ->
			...
	}
}
```

The compiler was happy to accept this, but of course didn't work as the types are wrong (boo -> Bool, true -> True). 
But it was puzzling for a bit. What even is `true` and `false` here? I guess this should be compiler error.

**Comment by lpil** [comment]
In that example 2 variables are being defined, one called "true", one called "false". These are just normal variable names in Gleam, there are no special keywords for booleans.

**Comment by sporto** [comment]
>  variables are being defined, one called "true"

Ok, but these variables don't exist anywhere in the code, shouldn't this raise a compiler error? Maybe when the exhaustiveness checker is done this won't be an issue?

**Comment by lpil** [comment]
This is defining a variable rather than using one, so it's typical that they don't exist before this code.

When we have exhaustiveness checking it'll warn that the second statement can never be reached. We could also have a warning for this specific scenario if we thought it might be a common mistake, to give a nicer error message

**Comment by sporto** [comment]
Oh, this make perfect sense now, I wasn't thinking about how variables need to be created when matching list, tuples, custom types, etc. This was just a confusion because of not using Gleam enough (mixing true and True). 

I'll will close this now. Thanks.
