### ISSUE TITLE
Generate accessors for structurally compatible multi-variant custom types

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#935]
As @CrowdHailer put it
> If you have
> ```rust
> type Foo {
>   A(id: Int)
>   B(id: Int)
>}
>```
>
> Should you be able to call?
> ```rust
> let foo = A(3)
> foo.id
>```

**Comment by CrowdHailer** [comment]
I wonder if you did that if you would also want.

```rust
let Foo(id: id , ..) = foo
let Foo(id, ..) == foo
```

Although the second one would suggest it's important if having the same field names that they are defined in the same order.
What happens if they have the same name but different order. Does only the first work.
That sounds like enough of a can of worms to not go there at all.

**Comment by lpil** [comment]
> Although the second one would suggest it's important if having the same field names that they are defined in the same order.

This is the case today! If you don't use labels it is order based.

**Comment by lpil** [comment]
Closing as no one else has brought it up since.

**Comment by lpil** [comment]
Harry wants this :)

**Comment by HarryET** [comment]
🙂
