### ISSUE TITLE
Support EEP 48 (compiling code documentation for use in Erlang etc)

### ISSUE THREAD

**Issue by lpil** [gleam-lang/gleam#941]

**Comment by J3RN** [comment]
Better yet, we should support [EEP 48](https://www.erlang.org/eeps/eep-0048) so that our documentation can be viewed from Erlang, Elixir, LFE, etc shells. The actual organization and storage of this information will be trivial if tedious, but the larger challenge will lie in updating the parser to retain `////` and `///` comments instead of discarding them.

**Comment by lpil** [comment]
Agreed, the parser rework will be the fiddly bit.

RE EEP 48, last I looked into this there was some suggestion of Erlang using a `-doc("...").` attribute, I wonder if that is usable yet.

**Comment by J3RN** [comment]
It appears that [EDoc](https://www.erlang.org/doc/apps/edoc/chapter.html) supports special `%% @doc ...` comments, alongside other more specific constructs such as `%% @author ...`, which it can then compile into the EEP 48-compliant "chunks".

**Comment by lpil** [comment]
Ah here we are, found it -> https://github.com/erlef/build-and-packaging-wg/issues/32

**Comment by J3RN** [comment]
Sadly José's Google Doc appears to have been deleted (or else I specifically don't have access 😅) and the EEP hasn't yet been created.

**Comment by lpil** [comment]
Closing as we don't have a clear idea of what to do here.
